from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.models.base import BaseModel, BaseModelUpdate, SQLModel
else:
    from app.models.base import BaseModel, BaseModelUpdate, SQLModel  # type: ignore

from app.models.account import (
    Account,
    AccountCreate,
    AccountPublic,
    AccountsPublic,
    AccountUpdate,
)
from app.models.asset_depreciation_schedule import (
    AssetDepreciationSchedule,
    AssetDepreciationScheduleCreate,
    AssetDepreciationSchedulePublic,
    AssetDepreciationSchedulesPublic,
)
from app.models.asset_transaction import (
    AssetTransaction,
    AssetTransactionCreate,
    AssetTransactionPublic,
    AssetTransactionsPublic,
)
from app.models.asset import (
    Asset,
    AssetBase,
    AssetCreate,
    AssetPublic,
    AssetsPublic,
    AssetUpdate,
)
from app.models.account_transaction import (
    AccountTransaction,
    AccountTransactionCreate,
    AccountTransactionPublic,
    AccountTransactionsPublic,
)
from app.models.main import (
    Message,
    Token,
    TokenPayload,
)
from app.models.organization import (
    Organization,
    OrganizationCreate,
    OrganizationPublic,
    OrganizationsPublic,
    OrganizationUpdate,
)
from app.models.organization_member import (
    OrganizationMember,
    OrganizationMemberCreate,
    OrganizationMemberPublic,
    OrganizationMembersPublic,
    OrganizationMemberUpdate,
    OrganizationRole,
    has_role_or_higher,
)
from app.models.payable import (
    Payable,
    PayableCreate,
    PayablePublic,
    PayablesPublic,
    PayableUpdate,
)
from app.models.payment import (
    Payment,
    PaymentCreate,
    PaymentPublic,
    PaymentsPublic,
    PaymentUpdate,
)
from app.models.permission import (
    Permission,
    PermissionCreate,
    PermissionPublic,
    PermissionsPublic,
    PermissionUpdate,
)
from app.models.purchase import (
    Purchase,
    PurchaseCreate,
    PurchasePublic,
    PurchasesPublic,
    PurchaseUpdate,
)
from app.models.purchase_item import ( # This is still needed as purchase_item refers to product (new)
    PurchaseItem,
    PurchaseItemCreate,
    PurchaseItemPublic,
    PurchaseItemsPublic,
    PurchaseItemUpdate,
)
from app.models.purchase_return import (
    PurchaseReturn,
    PurchaseReturnCreate,
    PurchaseReturnPublic,
    PurchaseReturnsPublic,
    PurchaseReturnUpdate,
)
from app.models.purchase_return_item import ( # This is still needed
    PurchaseReturnItem,
    PurchaseReturnItemCreate,
    PurchaseReturnItemPublic,
    PurchaseReturnItemsPublic,
    PurchaseReturnItemUpdate,
)
from app.models.receivable import (
    Receivable,
    ReceivableCreate,
    ReceivablePublic,
    ReceivablesPublic,
    ReceivableUpdate,
)
from app.models.role import (
    Role,
    RoleCreate,
    RolePublic,
    RolesPublic,
    RoleUpdate,
)
from app.models.role_permission import (
    RolePermission,
    RolePermissionCreate,
    RolePermissionPublic,
    RolePermissionsPublic,
    RolePermissionUpdate,
)
from app.models.sale import (
    Sale,
    SaleCreate,
    SalePublic,
    SalesPublic,
    SaleUpdate,
)
from app.models.sale_item import ( # This is still needed
    SaleItem,
    SaleItemCreate,
    SaleItemPublic,
    SaleItemsPublic,
    SaleItemUpdate,
)
from app.models.sale_return import (
    SaleReturn,
    SaleReturnCreate,
    SaleReturnPublic,
    SaleReturnsPublic,
    SaleReturnUpdate,
)
from app.models.sale_return_item import ( # This is still needed
    SaleReturnItem,
    SaleReturnItemCreate,
    SaleReturnItemPublic,
    SaleReturnItemsPublic,
    SaleReturnItemUpdate,
)
from app.models.stock_adjustment import (
    StockAdjustment,
    StockAdjustmentCreate,
    StockAdjustmentPublic,
    StockAdjustmentsPublic,
)
from app.models.stock_level import (
    StockLevel,
    StockLevelCreate,
    StockLevelPublic,
    StockLevelsPublic,
    StockLevelUpdate,
)
from app.models.stock_transfer import (
    StockTransfer,
    StockTransferCreate,
    StockTransferPublic,
    StockTransfersPublic,
)
from app.models.store import (
    Store,
    StoreCreate,
    StorePublic,
    StoresPublic,
    StoreUpdate,
)
from app.models.user import (
    NewPassword,
    UpdatePassword,
    User,
    UserCreate,
    UserPublic,
    UserRegister,
    UsersPublic,
    UserUpdate,
    UserUpdateMe,
)
from app.models.user_role import (
    UserRole,
    UserRoleCreate,
    UserRolePublic,
    UserRolesPublic,
    UserRoleUpdate,
)
from app.models.invoice import (
    Invoice,
    InvoiceCreate,
    InvoiceUpdate,
    InvoicePublic,
    InvoicesPublic,
    InvoiceStatus,
    VatDocumentType,
)
from app.models.invoice_line import (
    InvoiceLine,
    InvoiceLineCreate,
    InvoiceLineUpdate,
    InvoiceLinePublic,
    InvoiceLinesPublic,
)
from app.models.bank_account import (
    BankAccount,
    BankAccountCreate,
    BankAccountUpdate,
    BankAccountPublic,
    BankAccountsPublic,
    BankAccountType,
)
from app.models.bank_transaction import (
    BankTransaction,
    BankTransactionCreate,
    BankTransactionUpdate,
    BankTransactionPublic,
    BankTransactionsPublic,
)
from app.models.bank_statement import (
    BankStatement,
    BankStatementCreate,
    BankStatementUpdate,
    BankStatementPublic,
    BankStatementsPublic,
    BankStatementStatus,
)
from app.models.bank_import import (
    BankImport,
    BankImportCreate,
    BankImportUpdate,
    BankImportPublic,
    BankImportsPublic,
    BankImportType,
    BankImportStatus,
)
from app.models.bank_profile import (
    BankProfile,
    BankProfileCreate,
    BankProfileUpdate,
    BankProfilePublic,
    BankProfilesPublic,
    BankImportFormat,
)
from app.models.journal_entry import (
    JournalEntry,
    JournalEntryCreate,
    JournalEntryUpdate,
    JournalEntryPublic,
    JournalEntriesPublic,
)
from app.models.entry_line import (
    EntryLine,
    EntryLineCreate,
    EntryLineUpdate,
    EntryLinePublic,
    EntryLinesPublic,
)
from app.models.vat_return import (
    VatReturn,
    VatReturnCreate,
    VatReturnUpdate,
    VatReturnPublic,
    VatReturnsPublic,
    VatReturnStatus,
)
from app.models.vat_sales_register import (
    VatSalesRegister,
    VatSalesRegisterCreate,
    VatSalesRegisterUpdate,
    VatSalesRegisterPublic,
    VatSalesRegistersPublic,
)
from app.models.vat_purchase_register import (
    VatPurchaseRegister,
    VatPurchaseRegisterCreate,
    VatPurchaseRegisterUpdate,
    VatPurchaseRegisterPublic,
    VatPurchaseRegistersPublic,
    DeductibleCreditType,
)
from app.models.contraagent import (
    Contraagent,
    ContraagentCreate,
    ContraagentUpdate,
    ContraagentPublic,
    ContraagentsPublic,
)
from app.models.contraagent_bank_account import (
    ContraagentBankAccount,
    ContraagentBankAccountCreate,
    ContraagentBankAccountUpdate,
    ContraagentBankAccountPublic,
    ContraagentBankAccountsPublic,
)
from app.models.currency import (
    Currency,
    CurrencyCreate,
    CurrencyUpdate,
    CurrencyPublic,
    CurrenciesPublic,
)
from app.models.exchange_rate import (
    ExchangeRate,
    ExchangeRateCreate,
    ExchangeRateUpdate,
    ExchangeRatePublic,
    ExchangeRatesPublic,
)
from app.models.organization_settings import (
    OrganizationSettings,
    OrganizationSettingsCreate,
    OrganizationSettingsUpdate,
    OrganizationSettingsPublic,
    SmtpSettingsUpdate,
    AzureSettingsUpdate,
    DefaultAccountsUpdate,
    SmtpTestResult,
)
from app.models.document_upload import (
    DocumentUpload,
    DocumentUploadCreate,
    DocumentUploadUpdate,
    DocumentUploadPublic,
    DocumentUploadStatus,
)
from app.models.extracted_invoice import (
    ExtractedInvoice,
    ExtractedInvoiceCreate,
    ExtractedInvoiceUpdate,
    ExtractedInvoicePublic,
    ExtractedInvoicesPublic,
    ExtractedInvoiceStatus,
    ExtractedInvoiceType,
)

from app.models.item import (
    Item,
    ItemCreate,
    ItemUpdate,
    ItemPublic,
    ItemsPublic,
)
# Inventory module (from CyberERP)
from app.models.product import (
    Product,
    ProductCreate,
    ProductUpdate,
    ProductPublic,
    ProductsPublic,
    PRODUCT_CATEGORIES,
)
from app.models.measurement_unit import (
    MeasurementUnit,
    MeasurementUnitCreate,
    MeasurementUnitUpdate,
    MeasurementUnitPublic,
    MeasurementUnitsPublic,
    STANDARD_UNITS,
)
from app.models.product_unit import (
    ProductUnit,
    ProductUnitCreate,
    ProductUnitUpdate,
    ProductUnitPublic,
    ProductUnitsPublic,
)
from app.models.warehouse import (
    Warehouse,
    WarehouseCreate,
    WarehouseUpdate,
    WarehousePublic,
    WarehousesPublic,
    COSTING_METHODS,
)
from app.models.lot import (
    Lot,
    LotCreate,
    LotUpdate,
    LotPublic,
    LotsPublic,
)
from app.models.stock_movement import (
    StockMovement,
    StockMovementCreate,
    StockMovementUpdate,
    StockMovementPublic,
    StockMovementsPublic,
    MOVEMENT_TYPES,
    MOVEMENT_STATUSES,
)
from app.models.purchase_order import (
    PurchaseOrder,
    PurchaseOrderCreate,
    PurchaseOrderUpdate,
    PurchaseOrderPublic,
    PurchaseOrdersPublic,
    PurchaseOrderStatus,
    PurchaseOrderPriority,
)
from app.models.purchase_order_line import (
    PurchaseOrderLine,
    PurchaseOrderLineCreate,
    PurchaseOrderLineUpdate,
    PurchaseOrderLinePublic,
)
from app.models.quotation import (
    Quotation,
    QuotationCreate,
    QuotationUpdate,
    QuotationPublic,
    QuotationsPublic,
    QuotationStatus,
    QuotationPriority,
)
from app.models.quotation_line import (
    QuotationLine,
    QuotationLineCreate,
    QuotationLineUpdate,
    QuotationLinePublic,
)


__all__ = [
    "SQLModel",
    "BaseModel",
    "BaseModelUpdate",
    "Account",
    "AccountCreate",
    "AccountUpdate",
    "AccountPublic",
    "AccountsPublic",
    "AccountTransaction",
    "AccountTransactionCreate",
    "AccountTransactionPublic",
    "AccountTransactionsPublic",
    "Message",
    "Token",
    "TokenPayload",
    "Organization",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationPublic",
    "OrganizationsPublic",
    "OrganizationMember",
    "OrganizationMemberCreate",
    "OrganizationMemberUpdate",
    "OrganizationMemberPublic",
    "OrganizationMembersPublic",
    "OrganizationRole",
    "has_role_or_higher",
    "NewPassword",
    "Payment",
    "PaymentCreate",
    "PaymentPublic",
    "PaymentsPublic",
    "PurchaseItem",
    "PurchaseItemCreate",
    "PurchaseItemUpdate",
    "PurchaseItemPublic",
    "PurchaseItemsPublic",
    "Purchase",
    "PurchaseCreate",
    "PurchaseUpdate",
    "PurchasePublic",
    "PurchasesPublic",
    "PurchaseReturn",
    "PurchaseReturnCreate",
    "PurchaseReturnUpdate",
    "PurchaseReturnPublic",
    "PurchaseReturnsPublic",
    "Role",
    "RoleCreate",
    "RoleUpdate",
    "RolePublic",
    "RolesPublic",
    "Permission",
    "PermissionCreate",
    "PermissionUpdate",
    "PermissionPublic",
    "PermissionsPublic",
    "UserRole",
    "UserRoleCreate",
    "UserRoleUpdate",
    "UserRolePublic",
    "UserRolesPublic",
    "RolePermission",
    "RolePermissionCreate",
    "RolePermissionUpdate",
    "RolePermissionPublic",
    "RolePermissionsPublic",
    "SaleReturn",
    "SaleReturnCreate",
    "SaleReturnUpdate",
    "SaleReturnPublic",
    "SaleReturnsPublic",
    "PurchaseReturnItem",
    "PurchaseReturnItemCreate",
    "PurchaseReturnItemUpdate",
    "PurchaseReturnItemPublic",
    "PurchaseReturnItemsPublic",
    "SaleReturnItem",
    "SaleReturnItemCreate",
    "SaleReturnItemUpdate",
    "SaleReturnItemPublic",
    "SaleReturnItemsPublic",
    "SaleItem",
    "SaleItemCreate",
    "SaleItemUpdate",
    "SaleItemPublic",
    "SaleItemsPublic",
    "Sale",
    "SaleCreate",
    "SaleUpdate",
    "SalePublic",
    "SalesPublic",
    "StockAdjustment",
    "StockAdjustmentCreate",
    "StockAdjustmentPublic",
    "StockAdjustmentsPublic",
    "StockLevel",
    "StockLevelCreate",
    "StockLevelUpdate",
    "StockLevelPublic",
    "StockLevelsPublic",
    "StockTransfer",
    "StockTransferCreate",
    "StockTransferPublic",
    "StockTransfersPublic",
    "Store",
    "StoreCreate",
    "StoreUpdate",
    "StorePublic",
    "StoresPublic",
    "User",
    "UserCreate",
    "UserUpdate",
    "UserPublic",
    "UsersPublic",
    "UpdatePassword",
    "UserRegister",
    "UserUpdateMe",
    "Payable",
    "PayableCreate",
    "PayableUpdate",
    "PayablePublic",
    "PayablesPublic",
    "Receivable",
    "ReceivableCreate",
    "ReceivableUpdate",
    "ReceivablePublic",
    "ReceivablesPublic",
    "Invoice",
    "InvoiceCreate",
    "InvoiceUpdate",
    "InvoicePublic",
    "InvoicesPublic",
    "InvoiceStatus",
    "VatDocumentType",
    "InvoiceLine",
    "InvoiceLineCreate",
    "InvoiceLineUpdate",
    "InvoiceLinePublic",
    "InvoiceLinesPublic",
    # Bank module
    "BankAccount",
    "BankAccountCreate",
    "BankAccountUpdate",
    "BankAccountPublic",
    "BankAccountsPublic",
    "BankAccountType",
    "BankTransaction",
    "BankTransactionCreate",
    "BankTransactionUpdate",
    "BankTransactionPublic",
    "BankTransactionsPublic",
    "BankStatement",
    "BankStatementCreate",
    "BankStatementUpdate",
    "BankStatementPublic",
    "BankStatementsPublic",
    "BankStatementStatus",
    "BankImport",
    "BankImportCreate",
    "BankImportUpdate",
    "BankImportPublic",
    "BankImportsPublic",
    "BankImportType",
    "BankImportStatus",
    "BankProfile",
    "BankProfileCreate",
    "BankProfileUpdate",
    "BankProfilePublic",
    "BankProfilesPublic",
    "BankImportFormat",
    # Journal entries
    "JournalEntry",
    "JournalEntryCreate",
    "JournalEntryUpdate",
    "JournalEntryPublic",
    "JournalEntriesPublic",
    "EntryLine",
    "EntryLineCreate",
    "EntryLineUpdate",
    "EntryLinePublic",
    "EntryLinesPublic",
    # VAT module
    "VatReturn",
    "VatReturnCreate",
    "VatReturnUpdate",
    "VatReturnPublic",
    "VatReturnsPublic",
    "VatReturnStatus",
    "VatSalesRegister",
    "VatSalesRegisterCreate",
    "VatSalesRegisterUpdate",
    "VatSalesRegisterPublic",
    "VatSalesRegistersPublic",
    "VatPurchaseRegister",
    "VatPurchaseRegisterCreate",
    "VatPurchaseRegisterUpdate",
    "VatPurchaseRegisterPublic",
    "VatPurchaseRegistersPublic",
    "DeductibleCreditType",
    # Contraagent module
    "Contraagent",
    "ContraagentCreate",
    "ContraagentUpdate",
    "ContraagentPublic",
    "ContraagentsPublic",
    "ContraagentBankAccount",
    "ContraagentBankAccountCreate",
    "ContraagentBankAccountUpdate",
    "ContraagentBankAccountPublic",
    "ContraagentBankAccountsPublic",
    # Currency module
    "Currency",
    "CurrencyCreate",
    "CurrencyUpdate",
    "CurrencyPublic",
    "CurrenciesPublic",
    "ExchangeRate",
    "ExchangeRateCreate",
    "ExchangeRateUpdate",
    "ExchangeRatePublic",
    "ExchangeRatesPublic",
    # Organization settings
    "OrganizationSettings",
    "OrganizationSettingsCreate",
    "OrganizationSettingsUpdate",
    "OrganizationSettingsPublic",
    "SmtpSettingsUpdate",
    "AzureSettingsUpdate",
    "DefaultAccountsUpdate",
    "SmtpTestResult",
    # Document processing
    "DocumentUpload",
    "DocumentUploadCreate",
    "DocumentUploadUpdate",
    "DocumentUploadPublic",
    "DocumentUploadStatus",
    "ExtractedInvoice",
    "ExtractedInvoiceCreate",
    "ExtractedInvoiceUpdate",
    "ExtractedInvoicePublic",
    "ExtractedInvoicesPublic",
    "ExtractedInvoiceStatus",
    "ExtractedInvoiceType",
    # Manufacturing module
    "Recipe",
    "RecipeCreate",
    "RecipeUpdate",
    "RecipePublic",
    "RecipesPublic",
    "RecipeItem",
    "RecipeItemCreate",
    "RecipeItemUpdate",
    "RecipeItemPublic",
    "RecipeItemsPublic",
    # Item module
    "Item",
    "ItemCreate",
    "ItemUpdate",
    "ItemPublic",
    "ItemsPublic",
    # Purchase Order module
    "PurchaseOrder",
    "PurchaseOrderCreate",
    "PurchaseOrderUpdate",
    "PurchaseOrderPublic",
    "PurchaseOrdersPublic",
    "PurchaseOrderStatus",
    "PurchaseOrderPriority",
    "PurchaseOrderLine",
    "PurchaseOrderLineCreate",
    "PurchaseOrderLineUpdate",
    "PurchaseOrderLinePublic",
    # Quotation module
    "Quotation",
    "QuotationCreate",
    "QuotationUpdate",
    "QuotationPublic",
    "QuotationsPublic",
    "QuotationStatus",
    "QuotationPriority",
    "QuotationLine",
    "QuotationLineCreate",
    "QuotationLineUpdate",
    "QuotationLinePublic",
    # Inventory module (from CyberERP)
    "Product",
    "ProductCreate",
    "ProductUpdate",
    "ProductPublic",
    "ProductsPublic",
    "PRODUCT_CATEGORIES",
    "MeasurementUnit",
    "MeasurementUnitCreate",
    "MeasurementUnitUpdate",
    "MeasurementUnitPublic",
    "MeasurementUnitsPublic",
    "STANDARD_UNITS",
    "ProductUnit",
    "ProductUnitCreate",
    "ProductUnitUpdate",
    "ProductUnitPublic",
    "ProductUnitsPublic",
    "Warehouse",
    "WarehouseCreate",
    "WarehouseUpdate",
    "WarehousePublic",
    "WarehousesPublic",
    "COSTING_METHODS",
    "Lot",
    "LotCreate",
    "LotUpdate",
    "LotPublic",
    "LotsPublic",
    "StockMovement",
    "StockMovementCreate",
    "StockMovementUpdate",
    "StockMovementPublic",
    "StockMovementsPublic",
    "MOVEMENT_TYPES",
    "MOVEMENT_STATUSES",
]



# TODO: consider to add "is_deleted" column (soft-delete)
from app.models.recipe import (
    Recipe,
    RecipeCreate,
    RecipeUpdate,
    RecipePublic,
    RecipePublicWithItems,
    RecipesPublic,
)
from app.models.recipe_item import (
    RecipeItem,
    RecipeItemCreate,
    RecipeItemUpdate,
    RecipeItemPublic,
    RecipeItemsPublic,
)

# TODO: Rebuild invoice models when they are properly fixed
# The forward references need to be resolved for Pydantic v2
InvoiceCreate.model_rebuild()
InvoiceUpdate.model_rebuild()
InvoicePublic.model_rebuild()
InvoiceLinePublic.model_rebuild()