// This file is auto-generated by @hey-api/openapi-ts

export type AccountCreate = {
    code: string;
    name: string;
    account_type?: string;
    balance?: number;
    opening_balance?: number;
    is_debit_account?: boolean;
    is_active?: boolean;
    description?: (string | null);
};

export type AccountPublic = {
    code: string;
    name: string;
    account_type?: string;
    balance?: number;
    opening_balance?: number;
    is_debit_account?: boolean;
    is_active?: boolean;
    description?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type AccountsPublic = {
    data: Array<AccountPublic>;
    count: number;
};

export type AccountUpdate = {
    code?: (string | null);
    name?: (string | null);
    account_type?: (string | null);
    balance?: (number | null);
    opening_balance?: (number | null);
    is_debit_account?: (boolean | null);
    is_active?: (boolean | null);
    description?: (string | null);
};

export type AssetCreate = {
    code: string;
    name: string;
    category?: (string | null);
    inventory_number?: (string | null);
    serial_number?: (string | null);
    location?: (string | null);
    responsible_person?: (string | null);
    tax_category?: (string | null);
    tax_depreciation_rate?: (number | null);
    accounting_depreciation_rate?: (number | null);
    acquisition_date: string;
    acquisition_cost: number;
    startup_date?: (string | null);
    purchase_order_date?: (string | null);
    invoice_number?: (string | null);
    invoice_date?: (string | null);
    salvage_value?: number;
    useful_life_months: number;
    depreciation_method: string;
    status?: string;
    residual_value?: number;
    disposal_date?: (string | null);
    disposal_reason?: (string | null);
    disposal_value?: (number | null);
    notes?: (string | null);
    attachments?: ({
    [key: string]: unknown;
} | null);
    extra_metadata?: ({
    [key: string]: unknown;
} | null);
    month_value_change?: (number | null);
    month_suspension_resumption?: (number | null);
    month_writeoff_accounting?: (number | null);
    month_writeoff_tax?: (number | null);
    depreciation_months_current_year?: (number | null);
    acquisition_cost_begin_year?: (number | null);
    book_value_begin_year?: (number | null);
    accumulated_depreciation_begin_year?: (number | null);
    contraagent_id?: (string | null);
    accounting_account_id?: (string | null);
    expense_account_id?: (string | null);
    accumulated_depreciation_account_id?: (string | null);
    disposal_journal_entry_id?: (string | null);
};

export type AssetPublic = {
    code: string;
    name: string;
    category?: (string | null);
    inventory_number?: (string | null);
    serial_number?: (string | null);
    location?: (string | null);
    responsible_person?: (string | null);
    tax_category?: (string | null);
    tax_depreciation_rate?: (number | null);
    accounting_depreciation_rate?: (number | null);
    acquisition_date: string;
    acquisition_cost: number;
    startup_date?: (string | null);
    purchase_order_date?: (string | null);
    invoice_number?: (string | null);
    invoice_date?: (string | null);
    salvage_value?: number;
    useful_life_months: number;
    depreciation_method: string;
    status?: string;
    residual_value?: number;
    disposal_date?: (string | null);
    disposal_reason?: (string | null);
    disposal_value?: (number | null);
    notes?: (string | null);
    attachments?: ({
    [key: string]: unknown;
} | null);
    extra_metadata?: ({
    [key: string]: unknown;
} | null);
    month_value_change?: (number | null);
    month_suspension_resumption?: (number | null);
    month_writeoff_accounting?: (number | null);
    month_writeoff_tax?: (number | null);
    depreciation_months_current_year?: (number | null);
    acquisition_cost_begin_year?: (number | null);
    book_value_begin_year?: (number | null);
    accumulated_depreciation_begin_year?: (number | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type AssetsPublic = {
    data: Array<AssetPublic>;
    count: number;
};

export type AssetUpdate = {
    code: string;
    name: string;
    category?: (string | null);
    inventory_number?: (string | null);
    serial_number?: (string | null);
    location?: (string | null);
    responsible_person?: (string | null);
    tax_category?: (string | null);
    tax_depreciation_rate?: (number | null);
    accounting_depreciation_rate?: (number | null);
    acquisition_date: string;
    acquisition_cost: number;
    startup_date?: (string | null);
    purchase_order_date?: (string | null);
    invoice_number?: (string | null);
    invoice_date?: (string | null);
    salvage_value?: number;
    useful_life_months: number;
    depreciation_method: string;
    status?: string;
    residual_value?: number;
    disposal_date?: (string | null);
    disposal_reason?: (string | null);
    disposal_value?: (number | null);
    notes?: (string | null);
    attachments?: ({
    [key: string]: unknown;
} | null);
    extra_metadata?: ({
    [key: string]: unknown;
} | null);
    month_value_change?: (number | null);
    month_suspension_resumption?: (number | null);
    month_writeoff_accounting?: (number | null);
    month_writeoff_tax?: (number | null);
    depreciation_months_current_year?: (number | null);
    acquisition_cost_begin_year?: (number | null);
    book_value_begin_year?: (number | null);
    accumulated_depreciation_begin_year?: (number | null);
};

/**
 * Schema for updating only Azure settings.
 */
export type AzureSettingsUpdate = {
    azure_endpoint?: (string | null);
    azure_api_key?: (string | null);
    azure_model_id?: (string | null);
};

/**
 * Схема за създаване на банкова сметка.
 */
export type BankAccountCreate = {
    /**
     * Номер на сметката
     */
    account_no: string;
    /**
     * IBAN
     */
    iban: string;
    /**
     * BIC/SWIFT код
     */
    bic?: (string | null);
    /**
     * Тип сметка
     */
    account_type?: BankAccountType;
    /**
     * Валута
     */
    currency?: string;
    /**
     * Активна ли е сметката
     */
    is_active?: boolean;
    /**
     * Име на банката
     */
    bank_name: string;
    /**
     * Код на банката
     */
    bank_code?: (string | null);
    /**
     * Клон
     */
    branch_name?: (string | null);
    /**
     * Начално салдо
     */
    initial_balance?: (number | string);
    /**
     * Текущо салдо
     */
    current_balance?: (number | string);
    /**
     * Бележки
     */
    notes?: (string | null);
};

/**
 * Публична схема за банкова сметка.
 */
export type BankAccountPublic = {
    /**
     * Номер на сметката
     */
    account_no: string;
    /**
     * IBAN
     */
    iban: string;
    /**
     * BIC/SWIFT код
     */
    bic?: (string | null);
    /**
     * Тип сметка
     */
    account_type?: BankAccountType;
    /**
     * Валута
     */
    currency?: string;
    /**
     * Активна ли е сметката
     */
    is_active?: boolean;
    /**
     * Име на банката
     */
    bank_name: string;
    /**
     * Код на банката
     */
    bank_code?: (string | null);
    /**
     * Клон
     */
    branch_name?: (string | null);
    /**
     * Начално салдо
     */
    initial_balance?: string;
    /**
     * Текущо салдо
     */
    current_balance?: string;
    /**
     * Бележки
     */
    notes?: (string | null);
    id: string;
    organization_id: string;
    date_created: string;
    date_updated: string;
};

/**
 * Списък банкови сметки.
 */
export type BankAccountsPublic = {
    data: Array<BankAccountPublic>;
    count: number;
};

/**
 * Тип банкова сметка.
 */
export type BankAccountType = 'current' | 'savings' | 'foreign_currency';

/**
 * Схема за актуализация на банкова сметка.
 */
export type BankAccountUpdate = {
    account_no?: (string | null);
    iban?: (string | null);
    bic?: (string | null);
    account_type?: (BankAccountType | null);
    currency?: (string | null);
    is_active?: (boolean | null);
    bank_name?: (string | null);
    bank_code?: (string | null);
    branch_name?: (string | null);
    current_balance?: (number | string | null);
    notes?: (string | null);
};

/**
 * Схема за създаване на банкова транзакция.
 */
export type BankTransactionCreate = {
    /**
     * Дата на осчетоводяване
     */
    booking_date: string;
    /**
     * Вальор
     */
    value_date?: (string | null);
    /**
     * Сума
     */
    amount: (number | string);
    /**
     * Валута
     */
    currency?: string;
    /**
     * Кредитна транзакция (приход)
     */
    is_credit: boolean;
    /**
     * Описание
     */
    description?: (string | null);
    /**
     * Референция
     */
    reference?: (string | null);
    /**
     * Уникален ID на транзакцията
     */
    transaction_id?: (string | null);
    /**
     * Име на контрагент
     */
    counterpart_name?: (string | null);
    /**
     * IBAN на контрагент
     */
    counterpart_iban?: (string | null);
    /**
     * BIC на контрагент
     */
    counterpart_bic?: (string | null);
    /**
     * Обработена ли е
     */
    is_processed?: boolean;
    /**
     * Дата на обработка
     */
    processed_at?: (string | null);
    bank_account_id: string;
    bank_import_id?: (string | null);
    bank_profile_id?: (string | null);
    metadata_json?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Публична схема за банкова транзакция.
 */
export type BankTransactionPublic = {
    /**
     * Дата на осчетоводяване
     */
    booking_date: string;
    /**
     * Вальор
     */
    value_date?: (string | null);
    /**
     * Сума
     */
    amount: string;
    /**
     * Валута
     */
    currency?: string;
    /**
     * Кредитна транзакция (приход)
     */
    is_credit: boolean;
    /**
     * Описание
     */
    description?: (string | null);
    /**
     * Референция
     */
    reference?: (string | null);
    /**
     * Уникален ID на транзакцията
     */
    transaction_id?: (string | null);
    /**
     * Име на контрагент
     */
    counterpart_name?: (string | null);
    /**
     * IBAN на контрагент
     */
    counterpart_iban?: (string | null);
    /**
     * BIC на контрагент
     */
    counterpart_bic?: (string | null);
    /**
     * Обработена ли е
     */
    is_processed?: boolean;
    /**
     * Дата на обработка
     */
    processed_at?: (string | null);
    id: string;
    organization_id: string;
    bank_account_id: string;
    bank_import_id?: (string | null);
    bank_profile_id?: (string | null);
    journal_entry_id?: (string | null);
    date_created: string;
    date_updated: string;
};

/**
 * Списък банкови транзакции.
 */
export type BankTransactionsPublic = {
    data: Array<BankTransactionPublic>;
    count: number;
};

/**
 * Схема за актуализация на банкова транзакция.
 */
export type BankTransactionUpdate = {
    description?: (string | null);
    reference?: (string | null);
    counterpart_name?: (string | null);
    counterpart_iban?: (string | null);
    is_processed?: (boolean | null);
    journal_entry_id?: (string | null);
    metadata_json?: ({
    [key: string]: unknown;
} | null);
};

export type Body_ai_invoices_upload_invoice = {
    file: (Blob | File);
    invoice_type?: ExtractedInvoiceType;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContraagentBankAccountCreate = {
    iban: string;
    bic?: (string | null);
    bank_name?: (string | null);
    account_number?: (string | null);
    currency?: string;
    is_primary?: boolean;
    is_verified?: boolean;
    notes?: (string | null);
    contraagent_id: string;
};

export type ContraagentBankAccountPublic = {
    iban: string;
    bic?: (string | null);
    bank_name?: (string | null);
    account_number?: (string | null);
    currency?: string;
    is_primary?: boolean;
    is_verified?: boolean;
    notes?: (string | null);
    id: string;
    contraagent_id: string;
    date_created: string;
    date_updated: string;
    first_seen_at?: (string | null);
    last_seen_at?: (string | null);
    times_seen: number;
};

export type ContraagentBankAccountsPublic = {
    data: Array<ContraagentBankAccountPublic>;
    count: number;
};

export type ContraagentBankAccountUpdate = {
    iban?: (string | null);
    bic?: (string | null);
    bank_name?: (string | null);
    account_number?: (string | null);
    currency?: (string | null);
    is_primary?: (boolean | null);
    is_verified?: (boolean | null);
    notes?: (string | null);
};

export type ContraagentCreate = {
    name: string;
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    fax?: (string | null);
    is_company?: boolean;
    is_customer?: boolean;
    is_supplier?: boolean;
    is_active?: boolean;
    registration_number?: (string | null);
    vat_number?: (string | null);
    street_name?: (string | null);
    building_number?: (string | null);
    building?: (string | null);
    postal_code?: (string | null);
    city?: (string | null);
    region?: (string | null);
    country?: (string | null);
    additional_address_detail?: (string | null);
    contact_person_title?: (string | null);
    contact_person_first_name?: (string | null);
    contact_person_last_name?: (string | null);
    tax_type?: (string | null);
    tax_authority?: (string | null);
    tax_verification_date?: (string | null);
    self_billing_indicator?: boolean;
    related_party?: boolean;
    related_party_start_date?: (string | null);
    related_party_end_date?: (string | null);
    iban_number?: (string | null);
    bank_account_number?: (string | null);
    bank_sort_code?: (string | null);
    accounting_account_id?: (string | null);
    opening_debit_balance?: (number | string);
    opening_credit_balance?: (number | string);
    closing_debit_balance?: (number | string);
    closing_credit_balance?: (number | string);
    name_latin?: (string | null);
    name_cyrillic?: (string | null);
    notes?: (string | null);
};

export type ContraagentPublic = {
    name: string;
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    fax?: (string | null);
    is_company?: boolean;
    is_customer?: boolean;
    is_supplier?: boolean;
    is_active?: boolean;
    registration_number?: (string | null);
    vat_number?: (string | null);
    street_name?: (string | null);
    building_number?: (string | null);
    building?: (string | null);
    postal_code?: (string | null);
    city?: (string | null);
    region?: (string | null);
    country?: (string | null);
    additional_address_detail?: (string | null);
    contact_person_title?: (string | null);
    contact_person_first_name?: (string | null);
    contact_person_last_name?: (string | null);
    tax_type?: (string | null);
    tax_authority?: (string | null);
    tax_verification_date?: (string | null);
    self_billing_indicator?: boolean;
    related_party?: boolean;
    related_party_start_date?: (string | null);
    related_party_end_date?: (string | null);
    iban_number?: (string | null);
    bank_account_number?: (string | null);
    bank_sort_code?: (string | null);
    accounting_account_id?: (string | null);
    opening_debit_balance?: string;
    opening_credit_balance?: string;
    closing_debit_balance?: string;
    closing_credit_balance?: string;
    name_latin?: (string | null);
    name_cyrillic?: (string | null);
    notes?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
    accounting_account_name?: (string | null);
};

export type ContraagentsPublic = {
    data: Array<ContraagentPublic>;
    count: number;
};

export type ContraagentUpdate = {
    name?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    fax?: (string | null);
    is_company?: (boolean | null);
    is_customer?: (boolean | null);
    is_supplier?: (boolean | null);
    is_active?: (boolean | null);
    registration_number?: (string | null);
    vat_number?: (string | null);
    street_name?: (string | null);
    building_number?: (string | null);
    building?: (string | null);
    postal_code?: (string | null);
    city?: (string | null);
    region?: (string | null);
    country?: (string | null);
    additional_address_detail?: (string | null);
    contact_person_title?: (string | null);
    contact_person_first_name?: (string | null);
    contact_person_last_name?: (string | null);
    tax_type?: (string | null);
    tax_authority?: (string | null);
    tax_verification_date?: (string | null);
    self_billing_indicator?: (boolean | null);
    related_party?: (boolean | null);
    related_party_start_date?: (string | null);
    related_party_end_date?: (string | null);
    iban_number?: (string | null);
    bank_account_number?: (string | null);
    bank_sort_code?: (string | null);
    accounting_account_id?: (string | null);
    price_list_id?: (string | null);
    opening_debit_balance?: (number | string | null);
    opening_credit_balance?: (number | string | null);
    name_latin?: (string | null);
    name_cyrillic?: (string | null);
    notes?: (string | null);
};

export type CurrenciesPublic = {
    data: Array<CurrencyPublic>;
    count: number;
};

export type CurrencyCreate = {
    /**
     * ISO 4217 currency code (BGN, EUR, USD)
     */
    code: string;
    /**
     * English currency name
     */
    name: string;
    /**
     * Bulgarian currency name
     */
    name_bg?: (string | null);
    /**
     * Currency symbol (лв., €, $)
     */
    symbol?: (string | null);
    /**
     * Number of decimal places for amounts
     */
    decimal_places?: number;
    /**
     * Whether this currency is active
     */
    is_active?: boolean;
    /**
     * Whether this is the base currency
     */
    is_base_currency?: boolean;
    /**
     * Bulgarian National Bank code
     */
    bnb_code?: (string | null);
    /**
     * European Central Bank code
     */
    ecb_code?: (string | null);
    /**
     * Additional currency description
     */
    description?: (string | null);
};

export type CurrencyPublic = {
    /**
     * ISO 4217 currency code (BGN, EUR, USD)
     */
    code: string;
    /**
     * English currency name
     */
    name: string;
    /**
     * Bulgarian currency name
     */
    name_bg?: (string | null);
    /**
     * Currency symbol (лв., €, $)
     */
    symbol?: (string | null);
    /**
     * Number of decimal places for amounts
     */
    decimal_places?: number;
    /**
     * Whether this currency is active
     */
    is_active?: boolean;
    /**
     * Whether this is the base currency
     */
    is_base_currency?: boolean;
    /**
     * Bulgarian National Bank code
     */
    bnb_code?: (string | null);
    /**
     * European Central Bank code
     */
    ecb_code?: (string | null);
    /**
     * Additional currency description
     */
    description?: (string | null);
    id: string;
};

export type CurrencyUpdate = {
    /**
     * ISO 4217 currency code (BGN, EUR, USD)
     */
    code: string;
    /**
     * English currency name
     */
    name: string;
    /**
     * Bulgarian currency name
     */
    name_bg?: (string | null);
    /**
     * Currency symbol (лв., €, $)
     */
    symbol?: (string | null);
    /**
     * Number of decimal places for amounts
     */
    decimal_places?: number;
    /**
     * Whether this currency is active
     */
    is_active?: boolean;
    /**
     * Whether this is the base currency
     */
    is_base_currency?: boolean;
    /**
     * Bulgarian National Bank code
     */
    bnb_code?: (string | null);
    /**
     * European Central Bank code
     */
    ecb_code?: (string | null);
    /**
     * Additional currency description
     */
    description?: (string | null);
};

/**
 * Schema for updating only default accounts.
 */
export type DefaultAccountsUpdate = {
    default_clients_account_id?: (string | null);
    default_suppliers_account_id?: (string | null);
    default_vat_purchases_account_id?: (string | null);
    default_vat_sales_account_id?: (string | null);
    default_revenue_account_id?: (string | null);
    default_cash_account_id?: (string | null);
    default_bank_account_id?: (string | null);
};

export type ExchangeRatePublic = {
    /**
     * Source currency ID
     */
    from_currency_id: string;
    /**
     * Target currency ID
     */
    to_currency_id: string;
    /**
     * Exchange rate (from_currency -> to_currency)
     */
    rate: string;
    /**
     * Reverse exchange rate
     */
    reverse_rate?: (string | null);
    /**
     * Date when this rate is valid
     */
    valid_date: string;
    /**
     * Source of the rate: manual, bnb, ecb, api
     */
    rate_source?: string;
    /**
     * BNB rate identifier
     */
    bnb_rate_id?: (string | null);
    /**
     * ECB rate identifier
     */
    ecb_rate_id?: (string | null);
    /**
     * Whether this rate is active
     */
    is_active?: boolean;
    /**
     * Additional notes about the rate
     */
    notes?: (string | null);
    id: string;
};

export type ExchangeRatesPublic = {
    data: Array<ExchangeRatePublic>;
    count: number;
};

export type ExtractedInvoiceStatus = 'pending_review' | 'approved' | 'rejected' | 'converted';

export type ExtractedInvoiceType = 'sales' | 'purchase';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InvoiceCreate = {
    issue_date: string;
    due_date?: (string | null);
    tax_event_date?: (string | null);
    billing_name: string;
    billing_address?: (string | null);
    billing_vat_number?: (string | null);
    billing_company_id?: (string | null);
    subtotal?: (number | string);
    tax_amount?: (number | string);
    total_amount?: (number | string);
    paid_amount?: (number | string);
    /**
     * Invoice currency code (ISO 4217)
     */
    currency_code?: string;
    /**
     * Currency reference
     */
    currency_id?: (string | null);
    /**
     * Exchange rate to base currency
     */
    exchange_rate?: (number | string | null);
    /**
     * Whether this is a multi-currency invoice
     */
    is_multicurrency?: boolean;
    payment_method?: (string | null);
    notes?: (string | null);
    payment_terms?: (string | null);
    reference?: (string | null);
    vat_document_type?: string;
    vat_reason?: (string | null);
    oss_country?: (string | null);
    oss_vat_rate?: (number | string | null);
    contact_id: string;
    invoice_no: string;
    invoice_lines: Array<InvoiceLineCreate>;
};

export type InvoiceLineCreate = {
    description: string;
    quantity: (number | string);
    unit_of_measure?: string;
    unit_price: (number | string);
    discount_percent?: (number | string);
    tax_rate?: (number | string);
    product_id?: (string | null);
};

export type InvoiceLinePublic = {
    description: string;
    quantity: string;
    unit_of_measure?: string;
    unit_price: string;
    discount_percent?: string;
    tax_rate?: string;
    id: string;
    subtotal: string;
    tax_amount: string;
    total_amount: string;
    product?: (ProductPublic | null);
};

export type InvoicePublic = {
    issue_date: string;
    due_date?: (string | null);
    tax_event_date?: (string | null);
    billing_name: string;
    billing_address?: (string | null);
    billing_vat_number?: (string | null);
    billing_company_id?: (string | null);
    subtotal?: string;
    tax_amount?: string;
    total_amount?: string;
    paid_amount?: string;
    /**
     * Invoice currency code (ISO 4217)
     */
    currency_code?: string;
    /**
     * Currency reference
     */
    currency_id?: (string | null);
    /**
     * Exchange rate to base currency
     */
    exchange_rate?: (string | null);
    /**
     * Whether this is a multi-currency invoice
     */
    is_multicurrency?: boolean;
    payment_method?: (string | null);
    notes?: (string | null);
    payment_terms?: (string | null);
    reference?: (string | null);
    vat_document_type?: string;
    vat_reason?: (string | null);
    oss_country?: (string | null);
    oss_vat_rate?: (string | null);
    id: string;
    invoice_no: string;
    status: InvoiceStatus;
    contact: ContraagentPublic;
    invoice_lines: Array<InvoiceLinePublic>;
};

export type InvoicesPublic = {
    data: Array<InvoicePublic>;
    count: number;
};

export type InvoiceStatus = 'draft' | 'issued' | 'paid' | 'partially_paid' | 'overdue' | 'cancelled';

export type InvoiceType = {
    code: string;
    name: string;
};

export type JournalEntryCreate = {
    entry_date: string;
    description?: (string | null);
    currency_code?: string;
    exchange_rate?: (number | null);
    reference?: (string | null);
};

export type JournalEntryPublic = {
    entry_date: string;
    description?: (string | null);
    currency_code?: string;
    exchange_rate?: (number | null);
    reference?: (string | null);
    id: string;
    date_created: string;
    date_updated: string;
    organization_id: string;
    created_by_id: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationCreate = {
    name: string;
    name_latin?: (string | null);
    name_cyrillic?: (string | null);
    registration_number?: (string | null);
    vat_number?: (string | null);
    street_name?: (string | null);
    building_number?: (string | null);
    building?: (string | null);
    postal_code?: (string | null);
    city?: (string | null);
    region?: (string | null);
    country?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    is_active?: boolean;
    is_vat_registered?: boolean;
    tax_authority?: (string | null);
    tax_accounting_basis?: (string | null);
    currency_code?: (string | null);
    date_format?: (string | null);
    fiscal_year_start_date?: (string | null);
    bank_name?: (string | null);
    bank_account_number?: (string | null);
    bank_iban?: (string | null);
    bank_swift?: (string | null);
    legal_representative_name?: (string | null);
    legal_representative_id?: (string | null);
    notes?: (string | null);
};

export type OrganizationMemberCreate = {
    user_id: string;
    role?: OrganizationRole;
};

export type OrganizationMemberPublic = {
    role?: OrganizationRole;
    is_active?: boolean;
    id: string;
    user_id: string;
    organization_id: string;
    date_joined: string;
    date_updated: string;
};

export type OrganizationMembersPublic = {
    data: Array<OrganizationMemberPublic>;
    count: number;
};

export type OrganizationMemberUpdate = {
    role?: (OrganizationRole | null);
    is_active?: (boolean | null);
};

export type OrganizationPublic = {
    name: string;
    name_latin?: (string | null);
    name_cyrillic?: (string | null);
    registration_number?: (string | null);
    vat_number?: (string | null);
    street_name?: (string | null);
    building_number?: (string | null);
    building?: (string | null);
    postal_code?: (string | null);
    city?: (string | null);
    region?: (string | null);
    country?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    is_active?: boolean;
    is_vat_registered?: boolean;
    tax_authority?: (string | null);
    tax_accounting_basis?: (string | null);
    currency_code?: (string | null);
    date_format?: (string | null);
    fiscal_year_start_date?: (string | null);
    bank_name?: (string | null);
    bank_account_number?: (string | null);
    bank_iban?: (string | null);
    bank_swift?: (string | null);
    legal_representative_name?: (string | null);
    legal_representative_id?: (string | null);
    notes?: (string | null);
    id: string;
    date_created: string;
    date_updated: string;
};

/**
 * Роли в организацията с йерархия: ADMIN > MANAGER > MEMBER
 */
export type OrganizationRole = 'admin' | 'manager' | 'member';

/**
 * Public schema for organization settings.
 */
export type OrganizationSettingsPublic = {
    /**
     * SMTP сървър
     */
    smtp_host?: (string | null);
    /**
     * SMTP порт
     */
    smtp_port?: (number | null);
    /**
     * SMTP потребител
     */
    smtp_username?: (string | null);
    /**
     * SMTP парола
     */
    smtp_password?: (string | null);
    /**
     * Използвай TLS
     */
    smtp_use_tls?: boolean;
    /**
     * Имейл подател
     */
    smtp_from_email?: (string | null);
    /**
     * Име на подател
     */
    smtp_from_name?: (string | null);
    /**
     * Azure endpoint URL
     */
    azure_endpoint?: (string | null);
    /**
     * Azure API ключ
     */
    azure_api_key?: (string | null);
    /**
     * Azure model ID
     */
    azure_model_id?: (string | null);
    id: string;
    organization_id: string;
    default_clients_account_id?: (string | null);
    default_suppliers_account_id?: (string | null);
    default_vat_purchases_account_id?: (string | null);
    default_vat_sales_account_id?: (string | null);
    default_revenue_account_id?: (string | null);
    default_cash_account_id?: (string | null);
    default_bank_account_id?: (string | null);
    date_created: string;
    date_updated: string;
};

/**
 * Schema for updating organization settings.
 */
export type OrganizationSettingsUpdate = {
    smtp_host?: (string | null);
    smtp_port?: (number | null);
    smtp_username?: (string | null);
    smtp_password?: (string | null);
    smtp_use_tls?: (boolean | null);
    smtp_from_email?: (string | null);
    smtp_from_name?: (string | null);
    azure_endpoint?: (string | null);
    azure_api_key?: (string | null);
    azure_model_id?: (string | null);
    default_clients_account_id?: (string | null);
    default_suppliers_account_id?: (string | null);
    default_vat_purchases_account_id?: (string | null);
    default_vat_sales_account_id?: (string | null);
    default_revenue_account_id?: (string | null);
    default_cash_account_id?: (string | null);
    default_bank_account_id?: (string | null);
};

export type OrganizationsPublic = {
    data: Array<OrganizationPublic>;
    count: number;
};

export type OrganizationUpdate = {
    name?: (string | null);
    name_latin?: (string | null);
    name_cyrillic?: (string | null);
    registration_number?: (string | null);
    vat_number?: (string | null);
    street_name?: (string | null);
    building_number?: (string | null);
    building?: (string | null);
    postal_code?: (string | null);
    city?: (string | null);
    region?: (string | null);
    country?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    is_active?: boolean;
    is_vat_registered?: boolean;
    tax_authority?: (string | null);
    tax_accounting_basis?: (string | null);
    currency_code?: (string | null);
    date_format?: (string | null);
    fiscal_year_start_date?: (string | null);
    bank_name?: (string | null);
    bank_account_number?: (string | null);
    bank_iban?: (string | null);
    bank_swift?: (string | null);
    legal_representative_name?: (string | null);
    legal_representative_id?: (string | null);
    notes?: (string | null);
};

export type PaymentCreate = {
    date_payment: string;
    amount?: number;
    method: string;
    reference_id?: (string | null);
    description?: (string | null);
    transaction_type?: (string | null);
    transaction_id?: (string | null);
    subject_type?: (string | null);
    subject_id?: (string | null);
    is_reversal?: boolean;
    is_reversal_payment_id?: (string | null);
};

export type PaymentPublic = {
    date_payment: string;
    amount?: number;
    method: string;
    reference_id?: (string | null);
    description?: (string | null);
    transaction_type?: (string | null);
    transaction_id?: (string | null);
    subject_type?: (string | null);
    subject_id?: (string | null);
    is_reversal?: boolean;
    is_reversal_payment_id?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    account_id: string;
    date_created: string;
};

export type PaymentsPublic = {
    data: Array<PaymentPublic>;
    count: number;
};

export type PermissionCreate = {
    name: string;
    description?: (string | null);
};

export type PermissionPublic = {
    name: string;
    description?: (string | null);
    id: string;
    date_created: string;
    date_updated: string;
    organization_id: string;
    created_by_id: string;
    editor_id: string;
};

export type PermissionsPublic = {
    data: Array<PermissionPublic>;
    count: number;
};

export type PermissionUpdate = {
    name: (string | null);
    description?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Public product schema.
 */
export type ProductPublic = {
    /**
     * Product name
     */
    name: string;
    /**
     * Stock Keeping Unit code
     */
    sku: string;
    /**
     * Product description
     */
    description?: (string | null);
    /**
     * Category: goods, materials, services, produced
     */
    category?: string;
    /**
     * Selling price
     */
    price?: string;
    /**
     * Cost price
     */
    cost?: string;
    /**
     * Default unit
     */
    unit?: string;
    /**
     * Product barcode
     */
    barcode?: (string | null);
    /**
     * VAT rate %
     */
    tax_rate?: string;
    /**
     * Is product active
     */
    is_active?: boolean;
    /**
     * Track inventory levels
     */
    track_inventory?: boolean;
    /**
     * Opening stock quantity
     */
    opening_quantity?: string;
    /**
     * Opening stock value
     */
    opening_cost?: string;
    /**
     * Inventory account (304, 302, 303)
     */
    account_id?: (string | null);
    /**
     * Expense account (702, 601, 611)
     */
    expense_account_id?: (string | null);
    /**
     * Revenue account (702)
     */
    revenue_account_id?: (string | null);
    /**
     * Combined Nomenclature code (KN8)
     */
    cn_code?: (string | null);
    id: string;
    organization_id: string;
};

export type PurchaseCreate = {
    date_purchase: string;
    amount?: number;
    description?: (string | null);
    contraagent_id: string;
    store_id: string;
};

/**
 * Schema for creating a purchase order.
 */
export type PurchaseOrderCreate = {
    /**
     * Purchase order number
     */
    order_no: string;
    /**
     * Order date
     */
    order_date: string;
    /**
     * Expected delivery date
     */
    expected_delivery_date?: (string | null);
    /**
     * Contraagent reference number
     */
    contraagent_reference?: (string | null);
    /**
     * Contraagent contact person
     */
    contraagent_contact?: (string | null);
    /**
     * Delivery address
     */
    delivery_address?: (string | null);
    /**
     * Delivery instructions
     */
    delivery_instructions?: (string | null);
    subtotal?: (number | string);
    tax_amount?: (number | string);
    total_amount?: (number | string);
    discount_amount?: (number | string);
    discount_percent?: (number | string);
    /**
     * Currency code
     */
    currency_code?: string;
    exchange_rate?: (number | string | null);
    status?: PurchaseOrderStatus;
    priority?: PurchaseOrderPriority;
    notes?: (string | null);
    payment_terms?: (string | null);
    delivery_terms?: (string | null);
    internal_notes?: (string | null);
    /**
     * Employee who requested the order
     */
    requested_by?: (string | null);
    contraagent_id: string;
    warehouse_id?: (string | null);
    purchase_order_lines: Array<PurchaseOrderLineCreate>;
};

/**
 * Schema for creating a purchase order line.
 */
export type PurchaseOrderLineCreate = {
    product_id: string;
    /**
     * Product SKU/code
     */
    product_code: string;
    /**
     * Product name
     */
    product_name: string;
    /**
     * Line description
     */
    description?: (string | null);
    /**
     * Ordered quantity
     */
    quantity: (number | string);
    /**
     * Unit of measure
     */
    unit: string;
    /**
     * Unit price
     */
    unit_price: (number | string);
    /**
     * Discount percentage
     */
    discount_percent?: (number | string);
    /**
     * Discount amount
     */
    discount_amount?: (number | string);
    /**
     * VAT rate %
     */
    tax_rate?: (number | string);
    /**
     * VAT amount
     */
    tax_amount?: (number | string);
    /**
     * Line total before tax
     */
    line_total?: (number | string);
    /**
     * Line total with tax
     */
    line_total_with_tax?: (number | string);
    /**
     * Received quantity
     */
    received_quantity?: (number | string);
    /**
     * Remaining quantity to receive
     */
    remaining_quantity?: (number | string);
    /**
     * Expected delivery date for this line
     */
    expected_delivery_date?: (string | null);
    /**
     * Line notes
     */
    notes?: (string | null);
};

/**
 * Public purchase order line schema.
 */
export type PurchaseOrderLinePublic = {
    product_id: string;
    /**
     * Product SKU/code
     */
    product_code: string;
    /**
     * Product name
     */
    product_name: string;
    /**
     * Line description
     */
    description?: (string | null);
    /**
     * Ordered quantity
     */
    quantity: string;
    /**
     * Unit of measure
     */
    unit: string;
    /**
     * Unit price
     */
    unit_price: string;
    /**
     * Discount percentage
     */
    discount_percent?: string;
    /**
     * Discount amount
     */
    discount_amount?: string;
    /**
     * VAT rate %
     */
    tax_rate?: string;
    /**
     * VAT amount
     */
    tax_amount?: string;
    /**
     * Line total before tax
     */
    line_total?: string;
    /**
     * Line total with tax
     */
    line_total_with_tax?: string;
    /**
     * Received quantity
     */
    received_quantity?: string;
    /**
     * Remaining quantity to receive
     */
    remaining_quantity?: string;
    /**
     * Expected delivery date for this line
     */
    expected_delivery_date?: (string | null);
    /**
     * Line notes
     */
    notes?: (string | null);
    id: string;
    purchase_order_id: string;
};

/**
 * Schema for updating a purchase order line.
 */
export type PurchaseOrderLineUpdate = {
    product_id?: (string | null);
    product_code?: (string | null);
    product_name?: (string | null);
    description?: (string | null);
    quantity?: (number | string | null);
    unit?: (string | null);
    unit_price?: (number | string | null);
    discount_percent?: (number | string | null);
    discount_amount?: (number | string | null);
    tax_rate?: (number | string | null);
    tax_amount?: (number | string | null);
    line_total?: (number | string | null);
    line_total_with_tax?: (number | string | null);
    received_quantity?: (number | string | null);
    remaining_quantity?: (number | string | null);
    expected_delivery_date?: (string | null);
    notes?: (string | null);
};

/**
 * Purchase order priority levels.
 */
export type PurchaseOrderPriority = 'low' | 'normal' | 'high' | 'urgent';

/**
 * Public purchase order schema.
 */
export type PurchaseOrderPublic = {
    /**
     * Purchase order number
     */
    order_no: string;
    /**
     * Order date
     */
    order_date: string;
    /**
     * Expected delivery date
     */
    expected_delivery_date?: (string | null);
    /**
     * Contraagent reference number
     */
    contraagent_reference?: (string | null);
    /**
     * Contraagent contact person
     */
    contraagent_contact?: (string | null);
    /**
     * Delivery address
     */
    delivery_address?: (string | null);
    /**
     * Delivery instructions
     */
    delivery_instructions?: (string | null);
    subtotal?: string;
    tax_amount?: string;
    total_amount?: string;
    discount_amount?: string;
    discount_percent?: string;
    /**
     * Currency code
     */
    currency_code?: string;
    exchange_rate?: (string | null);
    status?: PurchaseOrderStatus;
    priority?: PurchaseOrderPriority;
    notes?: (string | null);
    payment_terms?: (string | null);
    delivery_terms?: (string | null);
    internal_notes?: (string | null);
    /**
     * Employee who requested the order
     */
    requested_by?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    contraagent_id: string;
    contraagent_name: string;
    warehouse_id?: (string | null);
    warehouse_name?: (string | null);
    date_created: string;
    date_updated: string;
    sent_date?: (string | null);
    confirmed_date?: (string | null);
    received_date?: (string | null);
    document_uid: string;
    purchase_order_lines: Array<PurchaseOrderLinePublic>;
};

/**
 * List of purchase orders with count.
 */
export type PurchaseOrdersPublic = {
    data: Array<PurchaseOrderPublic>;
    count: number;
};

/**
 * Purchase order status workflow.
 */
export type PurchaseOrderStatus = 'draft' | 'sent' | 'confirmed' | 'partially_received' | 'received' | 'cancelled' | 'closed';

/**
 * Schema for updating a purchase order.
 */
export type PurchaseOrderUpdate = {
    order_date?: (string | null);
    expected_delivery_date?: (string | null);
    contraagent_reference?: (string | null);
    contraagent_contact?: (string | null);
    delivery_address?: (string | null);
    delivery_instructions?: (string | null);
    subtotal?: (number | string | null);
    tax_amount?: (number | string | null);
    total_amount?: (number | string | null);
    discount_amount?: (number | string | null);
    discount_percent?: (number | string | null);
    currency_code?: (string | null);
    exchange_rate?: (number | string | null);
    status?: (PurchaseOrderStatus | null);
    priority?: (PurchaseOrderPriority | null);
    notes?: (string | null);
    payment_terms?: (string | null);
    delivery_terms?: (string | null);
    internal_notes?: (string | null);
    requested_by?: (string | null);
    warehouse_id?: (string | null);
    purchase_order_lines?: (Array<PurchaseOrderLineUpdate> | null);
};

export type PurchasePublic = {
    date_purchase: string;
    amount?: number;
    description?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    contraagent_id: string;
    contraagent_name: string;
    store_id: string;
    store_name: string;
    date_created: string;
    date_updated: string;
};

export type PurchasesPublic = {
    data: Array<PurchasePublic>;
    count: number;
};

export type PurchaseUpdate = {
    date_purchase?: (string | null);
    amount?: (number | null);
    description?: (string | null);
    contraagent_id?: (string | null);
    store_id?: (string | null);
};

/**
 * Schema for creating a quotation.
 */
export type QuotationCreate = {
    /**
     * Quotation number
     */
    quotation_no: string;
    /**
     * Quotation date
     */
    quotation_date: string;
    /**
     * Valid until date
     */
    valid_until: string;
    /**
     * Contraagent reference/PO number
     */
    contraagent_reference?: (string | null);
    /**
     * Contraagent contact person
     */
    contraagent_contact?: (string | null);
    /**
     * Billing address
     */
    billing_address?: (string | null);
    /**
     * Delivery address
     */
    delivery_address?: (string | null);
    /**
     * Delivery instructions
     */
    delivery_instructions?: (string | null);
    subtotal?: (number | string);
    tax_amount?: (number | string);
    total_amount?: (number | string);
    discount_amount?: (number | string);
    discount_percent?: (number | string);
    /**
     * Currency code
     */
    currency_code?: string;
    exchange_rate?: (number | string | null);
    status?: QuotationStatus;
    priority?: QuotationPriority;
    notes?: (string | null);
    payment_terms?: (string | null);
    delivery_terms?: (string | null);
    warranty_terms?: (string | null);
    internal_notes?: (string | null);
    /**
     * Sales person responsible
     */
    sales_person?: (string | null);
    /**
     * Follow-up date
     */
    follow_up_date?: (string | null);
    /**
     * Reason for rejection
     */
    rejection_reason?: (string | null);
    contraagent_id: string;
    probability?: (number | string | null);
    quotation_lines: Array<QuotationLineCreate>;
};

/**
 * Schema for creating a quotation line.
 */
export type QuotationLineCreate = {
    product_id: string;
    /**
     * Product SKU/code
     */
    product_code: string;
    /**
     * Product name
     */
    product_name: string;
    /**
     * Line description
     */
    description?: (string | null);
    /**
     * Quoted quantity
     */
    quantity: (number | string);
    /**
     * Unit of measure
     */
    unit: string;
    /**
     * Unit price
     */
    unit_price: (number | string);
    /**
     * Discount percentage
     */
    discount_percent?: (number | string);
    /**
     * Discount amount
     */
    discount_amount?: (number | string);
    /**
     * VAT rate %
     */
    tax_rate?: (number | string);
    /**
     * VAT amount
     */
    tax_amount?: (number | string);
    /**
     * Line total before tax
     */
    line_total?: (number | string);
    /**
     * Line total with tax
     */
    line_total_with_tax?: (number | string);
    /**
     * Whether this line is optional
     */
    optional?: boolean;
    /**
     * Alternative product suggestion
     */
    alternative_product?: (string | null);
    /**
     * Delivery time for this line
     */
    delivery_time?: (string | null);
    /**
     * Line notes
     */
    notes?: (string | null);
};

/**
 * Public quotation line schema.
 */
export type QuotationLinePublic = {
    product_id: string;
    /**
     * Product SKU/code
     */
    product_code: string;
    /**
     * Product name
     */
    product_name: string;
    /**
     * Line description
     */
    description?: (string | null);
    /**
     * Quoted quantity
     */
    quantity: string;
    /**
     * Unit of measure
     */
    unit: string;
    /**
     * Unit price
     */
    unit_price: string;
    /**
     * Discount percentage
     */
    discount_percent?: string;
    /**
     * Discount amount
     */
    discount_amount?: string;
    /**
     * VAT rate %
     */
    tax_rate?: string;
    /**
     * VAT amount
     */
    tax_amount?: string;
    /**
     * Line total before tax
     */
    line_total?: string;
    /**
     * Line total with tax
     */
    line_total_with_tax?: string;
    /**
     * Whether this line is optional
     */
    optional?: boolean;
    /**
     * Alternative product suggestion
     */
    alternative_product?: (string | null);
    /**
     * Delivery time for this line
     */
    delivery_time?: (string | null);
    /**
     * Line notes
     */
    notes?: (string | null);
    id: string;
    quotation_id: string;
};

/**
 * Schema for updating a quotation line.
 */
export type QuotationLineUpdate = {
    product_id?: (string | null);
    product_code?: (string | null);
    product_name?: (string | null);
    description?: (string | null);
    quantity?: (number | string | null);
    unit?: (string | null);
    unit_price?: (number | string | null);
    discount_percent?: (number | string | null);
    discount_amount?: (number | string | null);
    tax_rate?: (number | string | null);
    tax_amount?: (number | string | null);
    line_total?: (number | string | null);
    line_total_with_tax?: (number | string | null);
    optional?: (boolean | null);
    alternative_product?: (string | null);
    delivery_time?: (string | null);
    notes?: (string | null);
};

/**
 * Quotation priority levels.
 */
export type QuotationPriority = 'low' | 'normal' | 'high' | 'urgent';

/**
 * Public quotation schema.
 */
export type QuotationPublic = {
    /**
     * Quotation number
     */
    quotation_no: string;
    /**
     * Quotation date
     */
    quotation_date: string;
    /**
     * Valid until date
     */
    valid_until: string;
    /**
     * Contraagent reference/PO number
     */
    contraagent_reference?: (string | null);
    /**
     * Contraagent contact person
     */
    contraagent_contact?: (string | null);
    /**
     * Billing address
     */
    billing_address?: (string | null);
    /**
     * Delivery address
     */
    delivery_address?: (string | null);
    /**
     * Delivery instructions
     */
    delivery_instructions?: (string | null);
    subtotal?: string;
    tax_amount?: string;
    total_amount?: string;
    discount_amount?: string;
    discount_percent?: string;
    /**
     * Currency code
     */
    currency_code?: string;
    exchange_rate?: (string | null);
    status?: QuotationStatus;
    priority?: QuotationPriority;
    notes?: (string | null);
    payment_terms?: (string | null);
    delivery_terms?: (string | null);
    warranty_terms?: (string | null);
    internal_notes?: (string | null);
    /**
     * Sales person responsible
     */
    sales_person?: (string | null);
    /**
     * Follow-up date
     */
    follow_up_date?: (string | null);
    /**
     * Reason for rejection
     */
    rejection_reason?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    contraagent_id: string;
    contraagent_name: string;
    date_created: string;
    date_updated: string;
    sent_date?: (string | null);
    accepted_date?: (string | null);
    rejected_date?: (string | null);
    document_uid: string;
    probability?: (string | null);
    quotation_lines: Array<QuotationLinePublic>;
};

/**
 * List of quotations with count.
 */
export type QuotationsPublic = {
    data: Array<QuotationPublic>;
    count: number;
};

/**
 * Quotation status workflow.
 */
export type QuotationStatus = 'draft' | 'sent' | 'open' | 'accepted' | 'rejected' | 'expired' | 'converted_to_invoice' | 'cancelled';

/**
 * Schema for updating a quotation.
 */
export type QuotationUpdate = {
    quotation_date?: (string | null);
    valid_until?: (string | null);
    contraagent_reference?: (string | null);
    contraagent_contact?: (string | null);
    billing_address?: (string | null);
    delivery_address?: (string | null);
    delivery_instructions?: (string | null);
    subtotal?: (number | string | null);
    tax_amount?: (number | string | null);
    total_amount?: (number | string | null);
    discount_amount?: (number | string | null);
    discount_percent?: (number | string | null);
    currency_code?: (string | null);
    exchange_rate?: (number | string | null);
    status?: (QuotationStatus | null);
    priority?: (QuotationPriority | null);
    notes?: (string | null);
    payment_terms?: (string | null);
    delivery_terms?: (string | null);
    warranty_terms?: (string | null);
    internal_notes?: (string | null);
    sales_person?: (string | null);
    follow_up_date?: (string | null);
    rejection_reason?: (string | null);
    probability?: (number | string | null);
    quotation_lines?: (Array<QuotationLineUpdate> | null);
};

/**
 * Схема за създаване на рецепта.
 */
export type RecipeCreate = {
    /**
     * Уникален код на рецептата
     */
    code: string;
    /**
     * Наименование
     */
    name: string;
    description?: (string | null);
    /**
     * Изходно количество
     */
    output_quantity?: (number | string);
    /**
     * Мерна единица
     */
    unit?: string;
    /**
     * Версия на рецептата
     */
    version?: string;
    /**
     * Активна рецепта
     */
    is_active?: boolean;
    /**
     * Производствена цена
     */
    production_cost?: (number | string);
    notes?: (string | null);
    /**
     * ID на изходния продукт
     */
    output_item_id: string;
};

/**
 * Схема за създаване на компонент.
 */
export type RecipeItemCreate = {
    /**
     * Пореден номер на реда
     */
    line_no?: number;
    /**
     * Описание
     */
    description?: (string | null);
    /**
     * Количество
     */
    quantity: (number | string);
    /**
     * Мерна единица
     */
    unit?: string;
    /**
     * Процент брак/загуба
     */
    wastage_percent?: (number | string);
    /**
     * Цена на компонента
     */
    cost?: (number | string);
    notes?: (string | null);
    /**
     * ID на материала/продукта
     */
    product_id: string;
};

/**
 * Публична схема за компонент.
 */
export type RecipeItemPublic = {
    /**
     * Пореден номер на реда
     */
    line_no?: number;
    /**
     * Описание
     */
    description?: (string | null);
    /**
     * Количество
     */
    quantity: string;
    /**
     * Мерна единица
     */
    unit?: string;
    /**
     * Процент брак/загуба
     */
    wastage_percent?: string;
    /**
     * Цена на компонента
     */
    cost?: string;
    notes?: (string | null);
    id: string;
    recipe_id: string;
    product_id: string;
};

/**
 * Списък с компоненти.
 */
export type RecipeItemsPublic = {
    data: Array<RecipeItemPublic>;
    count: number;
};

/**
 * Схема за обновяване на компонент.
 */
export type RecipeItemUpdate = {
    line_no?: (number | null);
    description?: (string | null);
    quantity?: (number | string | null);
    unit?: (string | null);
    wastage_percent?: (number | string | null);
    cost?: (number | string | null);
    notes?: (string | null);
};

/**
 * Публична схема за рецепта.
 */
export type RecipePublic = {
    /**
     * Уникален код на рецептата
     */
    code: string;
    /**
     * Наименование
     */
    name: string;
    description?: (string | null);
    /**
     * Изходно количество
     */
    output_quantity?: string;
    /**
     * Мерна единица
     */
    unit?: string;
    /**
     * Версия на рецептата
     */
    version?: string;
    /**
     * Активна рецепта
     */
    is_active?: boolean;
    /**
     * Производствена цена
     */
    production_cost?: string;
    notes?: (string | null);
    id: string;
    output_item_id: string;
    organization_id: string;
    date_created: string;
    date_updated: string;
};

/**
 * Публична схема за рецепта с включени компоненти.
 */
export type RecipePublicWithItems = {
    /**
     * Уникален код на рецептата
     */
    code: string;
    /**
     * Наименование
     */
    name: string;
    description?: (string | null);
    /**
     * Изходно количество
     */
    output_quantity?: string;
    /**
     * Мерна единица
     */
    unit?: string;
    /**
     * Версия на рецептата
     */
    version?: string;
    /**
     * Активна рецепта
     */
    is_active?: boolean;
    /**
     * Производствена цена
     */
    production_cost?: string;
    notes?: (string | null);
    id: string;
    output_item_id: string;
    organization_id: string;
    date_created: string;
    date_updated: string;
    recipe_items?: Array<RecipeItemPublic>;
};

/**
 * Списък с рецепти.
 */
export type RecipesPublic = {
    data: Array<RecipePublic>;
    count: number;
};

/**
 * Схема за обновяване на рецепта.
 */
export type RecipeUpdate = {
    code?: (string | null);
    name?: (string | null);
    description?: (string | null);
    output_quantity?: (number | string | null);
    unit?: (string | null);
    version?: (string | null);
    is_active?: (boolean | null);
    production_cost?: (number | string | null);
    notes?: (string | null);
};

export type SaleCreate = {
    date_sale: string;
    amount?: number;
    description?: (string | null);
    contraagent_id: string;
    store_id: string;
};

export type SalePublic = {
    date_sale: string;
    amount?: number;
    description?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    contraagent_id: string;
    contraagent_name: string;
    store_id: string;
    store_name: string;
    date_created: string;
    date_updated: string;
};

export type SalesPublic = {
    data: Array<SalePublic>;
    count: number;
};

export type SaleUpdate = {
    date_sale?: (string | null);
    amount?: (number | null);
    description?: (string | null);
    contraagent_id?: (string | null);
    store_id?: (string | null);
};

/**
 * Schema for updating only SMTP settings.
 */
export type SmtpSettingsUpdate = {
    smtp_host?: (string | null);
    smtp_port?: (number | null);
    smtp_username?: (string | null);
    smtp_password?: (string | null);
    smtp_use_tls?: (boolean | null);
    smtp_from_email?: (string | null);
    smtp_from_name?: (string | null);
};

/**
 * Result of SMTP connection test.
 */
export type SmtpTestResult = {
    success: boolean;
    message: string;
};

/**
 * Schema for creating a stock level.
 */
export type StockLevelCreate = {
    /**
     * Quantity on hand
     */
    quantity_on_hand?: (number | string);
    /**
     * Reserved quantity
     */
    quantity_reserved?: (number | string);
    /**
     * Available quantity (on_hand - reserved)
     */
    quantity_available?: (number | string);
    /**
     * Minimum quantity threshold
     */
    minimum_quantity?: (number | string);
    /**
     * Reorder point
     */
    reorder_point?: (number | string);
    /**
     * Average cost per unit
     */
    average_cost?: (number | string | null);
    /**
     * Last purchase cost
     */
    last_cost?: (number | string | null);
    /**
     * Total inventory value
     */
    total_value?: (number | string | null);
    organization_id: string;
    product_id: string;
    warehouse_id: string;
};

/**
 * Public stock level schema.
 */
export type StockLevelPublic = {
    /**
     * Quantity on hand
     */
    quantity_on_hand?: string;
    /**
     * Reserved quantity
     */
    quantity_reserved?: string;
    /**
     * Available quantity (on_hand - reserved)
     */
    quantity_available?: string;
    /**
     * Minimum quantity threshold
     */
    minimum_quantity?: string;
    /**
     * Reorder point
     */
    reorder_point?: string;
    /**
     * Average cost per unit
     */
    average_cost?: (string | null);
    /**
     * Last purchase cost
     */
    last_cost?: (string | null);
    /**
     * Total inventory value
     */
    total_value?: (string | null);
    id: string;
    organization_id: string;
    product_id: string;
    warehouse_id: string;
};

/**
 * List of stock levels with count.
 */
export type StockLevelsPublic = {
    data: Array<StockLevelPublic>;
    count: number;
};

/**
 * Schema for updating a stock level.
 */
export type StockLevelUpdate = {
    quantity_on_hand?: (number | string | null);
    quantity_reserved?: (number | string | null);
    minimum_quantity?: (number | string | null);
    reorder_point?: (number | string | null);
    average_cost?: (number | string | null);
    last_cost?: (number | string | null);
};

export type StoreCreate = {
    name: string;
    address?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type StorePublic = {
    name: string;
    address?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type StoresPublic = {
    data: Array<StorePublic>;
    count: number;
};

export type StoreUpdate = {
    name?: (string | null);
    address?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    current_organization_id: (string | null);
    date_created: string;
    date_updated: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AccountsReadAccountsData = {
    limit?: number;
    skip?: number;
};

export type AccountsReadAccountsResponse = (AccountsPublic);

export type AccountsCreateAccountData = {
    requestBody: AccountCreate;
};

export type AccountsCreateAccountResponse = (AccountPublic);

export type AccountsReadAccountData = {
    id: string;
};

export type AccountsReadAccountResponse = (AccountPublic);

export type AccountsUpdateAccountData = {
    id: string;
    requestBody: AccountUpdate;
};

export type AccountsUpdateAccountResponse = (AccountPublic);

export type AccountsDeleteAccountData = {
    id: string;
};

export type AccountsDeleteAccountResponse = (Message);

export type AiInvoicesUploadInvoiceData = {
    formData: Body_ai_invoices_upload_invoice;
};

export type AiInvoicesUploadInvoiceResponse = (unknown);

export type AiInvoicesListExtractedInvoicesData = {
    limit?: number;
    offset?: number;
    status?: (ExtractedInvoiceStatus | null);
};

export type AiInvoicesListExtractedInvoicesResponse = (unknown);

export type AiInvoicesGetExtractedInvoiceData = {
    invoiceId: string;
};

export type AiInvoicesGetExtractedInvoiceResponse = (unknown);

export type AiInvoicesApproveExtractedInvoiceData = {
    invoiceId: string;
};

export type AiInvoicesApproveExtractedInvoiceResponse = (unknown);

export type AiInvoicesRejectExtractedInvoiceData = {
    invoiceId: string;
    rejectionReason: string;
};

export type AiInvoicesRejectExtractedInvoiceResponse = (unknown);

export type AiInvoicesGetProcessingStatsResponse = (unknown);

export type AssetsListAssetsData = {
    category?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    status?: (string | null);
};

export type AssetsListAssetsResponse = (AssetsPublic);

export type AssetsCreateAssetData = {
    requestBody: AssetCreate;
};

export type AssetsCreateAssetResponse = (AssetPublic);

export type AssetsGetAssetData = {
    assetId: string;
};

export type AssetsGetAssetResponse = (AssetPublic);

export type AssetsUpdateAssetData = {
    assetId: string;
    requestBody: AssetUpdate;
};

export type AssetsUpdateAssetResponse = (AssetPublic);

export type AssetsDeleteAssetData = {
    assetId: string;
};

export type AssetsDeleteAssetResponse = (unknown);

export type AssetsGetAssetStatisticsResponse = ({
    [key: string]: unknown;
});

export type BankAccountsListBankAccountsData = {
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type BankAccountsListBankAccountsResponse = (BankAccountsPublic);

export type BankAccountsCreateBankAccountData = {
    requestBody: BankAccountCreate;
};

export type BankAccountsCreateBankAccountResponse = (BankAccountPublic);

export type BankAccountsGetBankAccountData = {
    accountId: string;
};

export type BankAccountsGetBankAccountResponse = (BankAccountPublic);

export type BankAccountsUpdateBankAccountData = {
    accountId: string;
    requestBody: BankAccountUpdate;
};

export type BankAccountsUpdateBankAccountResponse = (BankAccountPublic);

export type BankAccountsDeleteBankAccountData = {
    accountId: string;
};

export type BankAccountsDeleteBankAccountResponse = (unknown);

export type BankTransactionsListBankTransactionsData = {
    bankAccountId?: (string | null);
    isCredit?: (boolean | null);
    isProcessed?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type BankTransactionsListBankTransactionsResponse = (BankTransactionsPublic);

export type BankTransactionsCreateBankTransactionData = {
    requestBody: BankTransactionCreate;
};

export type BankTransactionsCreateBankTransactionResponse = (BankTransactionPublic);

export type BankTransactionsGetBankTransactionData = {
    transactionId: string;
};

export type BankTransactionsGetBankTransactionResponse = (BankTransactionPublic);

export type BankTransactionsUpdateBankTransactionData = {
    requestBody: BankTransactionUpdate;
    transactionId: string;
};

export type BankTransactionsUpdateBankTransactionResponse = (BankTransactionPublic);

export type BankTransactionsDeleteBankTransactionData = {
    transactionId: string;
};

export type BankTransactionsDeleteBankTransactionResponse = (unknown);

export type BankTransactionsProcessBankTransactionData = {
    journalEntryId?: (string | null);
    transactionId: string;
};

export type BankTransactionsProcessBankTransactionResponse = (BankTransactionPublic);

export type ContraagentsReadContraagentsData = {
    /**
     * Filter by active status
     */
    isActive?: (boolean | null);
    /**
     * Filter by customer status
     */
    isCustomer?: (boolean | null);
    /**
     * Filter by supplier status
     */
    isSupplier?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ContraagentsReadContraagentsResponse = (ContraagentsPublic);

export type ContraagentsCreateContraagentData = {
    requestBody: ContraagentCreate;
    /**
     * Validate VAT number using VIES
     */
    validateVat?: boolean;
};

export type ContraagentsCreateContraagentResponse = (ContraagentPublic);

export type ContraagentsReadContraagentData = {
    id: string;
};

export type ContraagentsReadContraagentResponse = (ContraagentPublic);

export type ContraagentsUpdateContraagentData = {
    id: string;
    requestBody: ContraagentUpdate;
    /**
     * Validate VAT number using VIES
     */
    validateVat?: boolean;
};

export type ContraagentsUpdateContraagentResponse = (ContraagentPublic);

export type ContraagentsDeleteContraagentData = {
    id: string;
};

export type ContraagentsDeleteContraagentResponse = (Message);

export type ContraagentsValidateVatNumberData = {
    /**
     * VAT number to validate
     */
    vatNumber: string;
};

export type ContraagentsValidateVatNumberResponse = (unknown);

export type ContraagentsSetOpeningBalanceData = {
    /**
     * Opening credit balance
     */
    creditBalance?: (number | string);
    /**
     * Opening debit balance
     */
    debitBalance?: (number | string);
    /**
     * Description for journal entry
     */
    description?: (string | null);
    id: string;
};

export type ContraagentsSetOpeningBalanceResponse = (unknown);

export type ContraagentsRemoveOpeningBalanceData = {
    id: string;
};

export type ContraagentsRemoveOpeningBalanceResponse = (unknown);

export type ContraagentsGetOpeningBalancesSummaryResponse = (unknown);

export type ContraagentsReadContraagentBankAccountsData = {
    id: string;
};

export type ContraagentsReadContraagentBankAccountsResponse = (ContraagentBankAccountsPublic);

export type ContraagentsCreateContraagentBankAccountData = {
    id: string;
    requestBody: ContraagentBankAccountCreate;
};

export type ContraagentsCreateContraagentBankAccountResponse = (ContraagentBankAccountPublic);

export type ContraagentsUpdateContraagentBankAccountData = {
    bankAccountId: string;
    requestBody: ContraagentBankAccountUpdate;
};

export type ContraagentsUpdateContraagentBankAccountResponse = (ContraagentBankAccountPublic);

export type ContraagentsDeleteContraagentBankAccountData = {
    bankAccountId: string;
};

export type ContraagentsDeleteContraagentBankAccountResponse = (Message);

export type CurrenciesReadCurrenciesData = {
    limit?: number;
    skip?: number;
};

export type CurrenciesReadCurrenciesResponse = (CurrenciesPublic);

export type CurrenciesCreateCurrencyData = {
    requestBody: CurrencyCreate;
};

export type CurrenciesCreateCurrencyResponse = (CurrencyPublic);

export type CurrenciesUpdateCurrencyData = {
    id: string;
    requestBody: CurrencyUpdate;
};

export type CurrenciesUpdateCurrencyResponse = (CurrencyPublic);

export type CurrenciesReadCurrencyData = {
    id: string;
};

export type CurrenciesReadCurrencyResponse = (CurrencyPublic);

export type CurrenciesDeleteCurrencyData = {
    id: string;
};

export type CurrenciesDeleteCurrencyResponse = (CurrencyPublic);

export type CurrenciesReadExchangeRatesData = {
    limit?: number;
    skip?: number;
};

export type CurrenciesReadExchangeRatesResponse = (ExchangeRatesPublic);

export type CurrenciesUpdateEcbRatesResponse = ({
    [key: string]: unknown;
});

export type InvoicesReadInvoicesData = {
    limit?: number;
    skip?: number;
};

export type InvoicesReadInvoicesResponse = (InvoicesPublic);

export type InvoicesCreateInvoiceData = {
    requestBody: InvoiceCreate;
};

export type InvoicesCreateInvoiceResponse = (InvoicePublic);

export type InvoicesDownloadInvoicePdfData = {
    id: string;
};

export type InvoicesDownloadInvoicePdfResponse = (unknown);

export type JournalEntriesReadJournalEntriesData = {
    limit?: number;
    skip?: number;
};

export type JournalEntriesReadJournalEntriesResponse = (Array<JournalEntryPublic>);

export type JournalEntriesCreateJournalEntryData = {
    requestBody: JournalEntryCreate;
};

export type JournalEntriesCreateJournalEntryResponse = (JournalEntryPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OrganizationsReadOrganizationsData = {
    limit?: number;
    skip?: number;
};

export type OrganizationsReadOrganizationsResponse = (OrganizationsPublic);

export type OrganizationsCreateOrganizationData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadCurrentOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadOrganizationData = {
    id: string;
};

export type OrganizationsReadOrganizationResponse = (OrganizationPublic);

export type OrganizationsUpdateOrganizationData = {
    id: string;
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateOrganizationResponse = (OrganizationPublic);

export type OrganizationsDeleteOrganizationData = {
    id: string;
};

export type OrganizationsDeleteOrganizationResponse = (Message);

export type OrganizationsSwitchOrganizationData = {
    id: string;
};

export type OrganizationsSwitchOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadOrganizationMembersData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type OrganizationsReadOrganizationMembersResponse = (OrganizationMembersPublic);

export type OrganizationsAddOrganizationMemberData = {
    id: string;
    requestBody: OrganizationMemberCreate;
};

export type OrganizationsAddOrganizationMemberResponse = (OrganizationMemberPublic);

export type OrganizationsUpdateOrganizationMemberData = {
    id: string;
    requestBody: OrganizationMemberUpdate;
    userId: string;
};

export type OrganizationsUpdateOrganizationMemberResponse = (OrganizationMemberPublic);

export type OrganizationsRemoveOrganizationMemberData = {
    id: string;
    userId: string;
};

export type OrganizationsRemoveOrganizationMemberResponse = (Message);

export type OrganizationSettingsGetSettingsResponse = (OrganizationSettingsPublic);

export type OrganizationSettingsUpdateSettingsData = {
    requestBody: OrganizationSettingsUpdate;
};

export type OrganizationSettingsUpdateSettingsResponse = (OrganizationSettingsPublic);

export type OrganizationSettingsUpdateSmtpSettingsData = {
    requestBody: SmtpSettingsUpdate;
};

export type OrganizationSettingsUpdateSmtpSettingsResponse = (OrganizationSettingsPublic);

export type OrganizationSettingsUpdateAzureSettingsData = {
    requestBody: AzureSettingsUpdate;
};

export type OrganizationSettingsUpdateAzureSettingsResponse = (OrganizationSettingsPublic);

export type OrganizationSettingsUpdateDefaultAccountsData = {
    requestBody: DefaultAccountsUpdate;
};

export type OrganizationSettingsUpdateDefaultAccountsResponse = (OrganizationSettingsPublic);

export type OrganizationSettingsTestSmtpConnectionResponse = (SmtpTestResult);

export type PaymentsReadPaymentsData = {
    limit?: number;
    skip?: number;
};

export type PaymentsReadPaymentsResponse = (PaymentsPublic);

export type PaymentsCreatePaymentData = {
    requestBody: PaymentCreate;
};

export type PaymentsCreatePaymentResponse = (PaymentPublic);

export type PermissionsReadPermissionsData = {
    limit?: number;
    skip?: number;
};

export type PermissionsReadPermissionsResponse = (PermissionsPublic);

export type PermissionsCreatePermissionData = {
    requestBody: PermissionCreate;
};

export type PermissionsCreatePermissionResponse = (PermissionPublic);

export type PermissionsReadPermissionData = {
    id: string;
};

export type PermissionsReadPermissionResponse = (PermissionPublic);

export type PermissionsUpdatePermissionData = {
    id: string;
    requestBody: PermissionUpdate;
};

export type PermissionsUpdatePermissionResponse = (PermissionPublic);

export type PermissionsDeletePermissionData = {
    id: string;
};

export type PermissionsDeletePermissionResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PurchaseOrdersReadPurchaseOrdersData = {
    contraagentId?: (string | null);
    limit?: number;
    skip?: number;
    status?: (PurchaseOrderStatus | null);
};

export type PurchaseOrdersReadPurchaseOrdersResponse = (PurchaseOrdersPublic);

export type PurchaseOrdersCreatePurchaseOrderData = {
    requestBody: PurchaseOrderCreate;
};

export type PurchaseOrdersCreatePurchaseOrderResponse = (PurchaseOrderPublic);

export type PurchaseOrdersReadPurchaseOrderData = {
    id: string;
};

export type PurchaseOrdersReadPurchaseOrderResponse = (PurchaseOrderPublic);

export type PurchaseOrdersUpdatePurchaseOrderData = {
    id: string;
    requestBody: PurchaseOrderUpdate;
};

export type PurchaseOrdersUpdatePurchaseOrderResponse = (PurchaseOrderPublic);

export type PurchaseOrdersDeletePurchaseOrderData = {
    id: string;
};

export type PurchaseOrdersDeletePurchaseOrderResponse = (Message);

export type PurchaseOrdersSendPurchaseOrderData = {
    id: string;
};

export type PurchaseOrdersSendPurchaseOrderResponse = (Message);

export type PurchaseOrdersConfirmPurchaseOrderData = {
    id: string;
};

export type PurchaseOrdersConfirmPurchaseOrderResponse = (Message);

export type PurchaseOrdersCancelPurchaseOrderData = {
    id: string;
};

export type PurchaseOrdersCancelPurchaseOrderResponse = (Message);

export type PurchasesReadPurchasesData = {
    limit?: number;
    skip?: number;
};

export type PurchasesReadPurchasesResponse = (PurchasesPublic);

export type PurchasesCreatePurchaseData = {
    requestBody: PurchaseCreate;
};

export type PurchasesCreatePurchaseResponse = (PurchasePublic);

export type PurchasesReadPurchaseData = {
    id: string;
};

export type PurchasesReadPurchaseResponse = (PurchasePublic);

export type PurchasesUpdatePurchaseData = {
    id: string;
    requestBody: PurchaseUpdate;
};

export type PurchasesUpdatePurchaseResponse = (PurchasePublic);

export type PurchasesDeletePurchaseData = {
    id: string;
};

export type PurchasesDeletePurchaseResponse = (Message);

export type QuotationsReadQuotationsData = {
    contraagentId?: (string | null);
    limit?: number;
    skip?: number;
    status?: (QuotationStatus | null);
};

export type QuotationsReadQuotationsResponse = (QuotationsPublic);

export type QuotationsCreateQuotationData = {
    requestBody: QuotationCreate;
};

export type QuotationsCreateQuotationResponse = (QuotationPublic);

export type QuotationsReadQuotationData = {
    id: string;
};

export type QuotationsReadQuotationResponse = (QuotationPublic);

export type QuotationsUpdateQuotationData = {
    id: string;
    requestBody: QuotationUpdate;
};

export type QuotationsUpdateQuotationResponse = (QuotationPublic);

export type QuotationsDeleteQuotationData = {
    id: string;
};

export type QuotationsDeleteQuotationResponse = (Message);

export type QuotationsSendQuotationData = {
    id: string;
};

export type QuotationsSendQuotationResponse = (Message);

export type QuotationsAcceptQuotationData = {
    id: string;
};

export type QuotationsAcceptQuotationResponse = (Message);

export type QuotationsRejectQuotationData = {
    id: string;
    rejectionReason: string;
};

export type QuotationsRejectQuotationResponse = (Message);

export type QuotationsCancelQuotationData = {
    id: string;
};

export type QuotationsCancelQuotationResponse = (Message);

export type QuotationsConvertQuotationToInvoiceData = {
    id: string;
};

export type QuotationsConvertQuotationToInvoiceResponse = (Message);

export type RecipesReadRecipesData = {
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type RecipesReadRecipesResponse = (RecipesPublic);

export type RecipesCreateRecipeEndpointData = {
    requestBody: RecipeCreate;
};

export type RecipesCreateRecipeEndpointResponse = (RecipePublic);

export type RecipesReadRecipeData = {
    recipeId: string;
};

export type RecipesReadRecipeResponse = (RecipePublicWithItems);

export type RecipesUpdateRecipeEndpointData = {
    recipeId: string;
    requestBody: RecipeUpdate;
};

export type RecipesUpdateRecipeEndpointResponse = (RecipePublic);

export type RecipesDeleteRecipeEndpointData = {
    recipeId: string;
};

export type RecipesDeleteRecipeEndpointResponse = (Message);

export type RecipesActivateRecipeData = {
    recipeId: string;
};

export type RecipesActivateRecipeResponse = (RecipePublic);

export type RecipesDeactivateRecipeData = {
    recipeId: string;
};

export type RecipesDeactivateRecipeResponse = (RecipePublic);

export type RecipesReadRecipeItemsData = {
    recipeId: string;
};

export type RecipesReadRecipeItemsResponse = (RecipeItemsPublic);

export type RecipesCreateRecipeItemEndpointData = {
    recipeId: string;
    requestBody: RecipeItemCreate;
};

export type RecipesCreateRecipeItemEndpointResponse = (RecipeItemPublic);

export type RecipesUpdateRecipeItemEndpointData = {
    productId: string;
    recipeId: string;
    requestBody: RecipeItemUpdate;
};

export type RecipesUpdateRecipeItemEndpointResponse = (RecipeItemPublic);

export type RecipesDeleteRecipeItemEndpointData = {
    productId: string;
    recipeId: string;
};

export type RecipesDeleteRecipeItemEndpointResponse = (Message);

export type SaftGenerateSaftData = {
    month?: (number | null);
    reportType: string;
    year: number;
};

export type SaftGenerateSaftResponse = (unknown);

export type SaftGenerateVatSalesRegisterData = {
    month: number;
    year: number;
};

export type SaftGenerateVatSalesRegisterResponse = (unknown);

export type SaftGenerateVatPurchaseRegisterData = {
    month: number;
    year: number;
};

export type SaftGenerateVatPurchaseRegisterResponse = (unknown);

export type SaftGenerateVatDeclarationData = {
    month: number;
    year: number;
};

export type SaftGenerateVatDeclarationResponse = (unknown);

export type SalesReadSalesData = {
    limit?: number;
    skip?: number;
};

export type SalesReadSalesResponse = (SalesPublic);

export type SalesCreateSaleData = {
    requestBody: SaleCreate;
};

export type SalesCreateSaleResponse = (SalePublic);

export type SalesReadSaleData = {
    id: string;
};

export type SalesReadSaleResponse = (SalePublic);

export type SalesUpdateSaleData = {
    id: string;
    requestBody: SaleUpdate;
};

export type SalesUpdateSaleResponse = (SalePublic);

export type SalesDeleteSaleData = {
    id: string;
};

export type SalesDeleteSaleResponse = (Message);

export type StockLevelsReadStockLevelsData = {
    limit?: number;
    skip?: number;
};

export type StockLevelsReadStockLevelsResponse = (StockLevelsPublic);

export type StockLevelsCreateStockLevelData = {
    requestBody: StockLevelCreate;
};

export type StockLevelsCreateStockLevelResponse = (StockLevelPublic);

export type StockLevelsReadStockLevelData = {
    id: string;
};

export type StockLevelsReadStockLevelResponse = (StockLevelPublic);

export type StockLevelsUpdateStockLevelData = {
    id: string;
    requestBody: StockLevelUpdate;
};

export type StockLevelsUpdateStockLevelResponse = (StockLevelPublic);

export type StockLevelsDeleteStockLevelData = {
    id: string;
};

export type StockLevelsDeleteStockLevelResponse = (Message);

export type StoresReadStoresData = {
    limit?: number;
    skip?: number;
};

export type StoresReadStoresResponse = (StoresPublic);

export type StoresCreateStoreData = {
    requestBody: StoreCreate;
};

export type StoresCreateStoreResponse = (StorePublic);

export type StoresReadStoreData = {
    id: string;
};

export type StoresReadStoreResponse = (StorePublic);

export type StoresUpdateStoreData = {
    id: string;
    requestBody: StoreUpdate;
};

export type StoresUpdateStoreResponse = (StorePublic);

export type StoresDeleteStoreData = {
    id: string;
};

export type StoresDeleteStoreResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadSpecialData = {
    limit?: number;
    skip?: number;
};

export type UsersReadSpecialResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsReadInvoiceTypesResponse = (Array<InvoiceType>);

export type VatDownloadSalesRegisterData = {
    month?: number;
    year?: number;
};

export type VatDownloadSalesRegisterResponse = (unknown);

export type VatDownloadPurchaseRegisterData = {
    month?: number;
    year?: number;
};

export type VatDownloadPurchaseRegisterResponse = (unknown);

export type VatDownloadVatDeclarationData = {
    month?: number;
    year?: number;
};

export type VatDownloadVatDeclarationResponse = (unknown);