// This file is auto-generated by @hey-api/openapi-ts

export type AccountCreate = {
    code: string;
    name: string;
    account_type?: string;
    balance?: number;
    opening_balance?: number;
    is_debit_account?: boolean;
    is_active?: boolean;
    description?: (string | null);
};

export type AccountPublic = {
    code: string;
    name: string;
    account_type?: string;
    balance?: number;
    opening_balance?: number;
    is_debit_account?: boolean;
    is_active?: boolean;
    description?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type AccountsPublic = {
    data: Array<AccountPublic>;
    count: number;
};

export type AccountUpdate = {
    code?: (string | null);
    name?: (string | null);
    account_type?: (string | null);
    balance?: (number | null);
    opening_balance?: (number | null);
    is_debit_account?: (boolean | null);
    is_active?: (boolean | null);
    description?: (string | null);
};

export type AssetCreate = {
    code: string;
    name: string;
    category?: (string | null);
    inventory_number?: (string | null);
    serial_number?: (string | null);
    location?: (string | null);
    responsible_person?: (string | null);
    tax_category?: (string | null);
    tax_depreciation_rate?: (number | null);
    accounting_depreciation_rate?: (number | null);
    acquisition_date: string;
    acquisition_cost: number;
    startup_date?: (string | null);
    purchase_order_date?: (string | null);
    invoice_number?: (string | null);
    invoice_date?: (string | null);
    salvage_value?: number;
    useful_life_months: number;
    depreciation_method: string;
    status?: string;
    residual_value?: number;
    disposal_date?: (string | null);
    disposal_reason?: (string | null);
    disposal_value?: (number | null);
    notes?: (string | null);
    attachments?: ({
    [key: string]: unknown;
} | null);
    extra_metadata?: ({
    [key: string]: unknown;
} | null);
    month_value_change?: (number | null);
    month_suspension_resumption?: (number | null);
    month_writeoff_accounting?: (number | null);
    month_writeoff_tax?: (number | null);
    depreciation_months_current_year?: (number | null);
    acquisition_cost_begin_year?: (number | null);
    book_value_begin_year?: (number | null);
    accumulated_depreciation_begin_year?: (number | null);
    supplier_id?: (string | null);
    accounting_account_id?: (string | null);
    expense_account_id?: (string | null);
    accumulated_depreciation_account_id?: (string | null);
    disposal_journal_entry_id?: (string | null);
};

export type AssetPublic = {
    code: string;
    name: string;
    category?: (string | null);
    inventory_number?: (string | null);
    serial_number?: (string | null);
    location?: (string | null);
    responsible_person?: (string | null);
    tax_category?: (string | null);
    tax_depreciation_rate?: (number | null);
    accounting_depreciation_rate?: (number | null);
    acquisition_date: string;
    acquisition_cost: number;
    startup_date?: (string | null);
    purchase_order_date?: (string | null);
    invoice_number?: (string | null);
    invoice_date?: (string | null);
    salvage_value?: number;
    useful_life_months: number;
    depreciation_method: string;
    status?: string;
    residual_value?: number;
    disposal_date?: (string | null);
    disposal_reason?: (string | null);
    disposal_value?: (number | null);
    notes?: (string | null);
    attachments?: ({
    [key: string]: unknown;
} | null);
    extra_metadata?: ({
    [key: string]: unknown;
} | null);
    month_value_change?: (number | null);
    month_suspension_resumption?: (number | null);
    month_writeoff_accounting?: (number | null);
    month_writeoff_tax?: (number | null);
    depreciation_months_current_year?: (number | null);
    acquisition_cost_begin_year?: (number | null);
    book_value_begin_year?: (number | null);
    accumulated_depreciation_begin_year?: (number | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type AssetsPublic = {
    data: Array<AssetPublic>;
    count: number;
};

export type AssetUpdate = {
    code: string;
    name: string;
    category?: (string | null);
    inventory_number?: (string | null);
    serial_number?: (string | null);
    location?: (string | null);
    responsible_person?: (string | null);
    tax_category?: (string | null);
    tax_depreciation_rate?: (number | null);
    accounting_depreciation_rate?: (number | null);
    acquisition_date: string;
    acquisition_cost: number;
    startup_date?: (string | null);
    purchase_order_date?: (string | null);
    invoice_number?: (string | null);
    invoice_date?: (string | null);
    salvage_value?: number;
    useful_life_months: number;
    depreciation_method: string;
    status?: string;
    residual_value?: number;
    disposal_date?: (string | null);
    disposal_reason?: (string | null);
    disposal_value?: (number | null);
    notes?: (string | null);
    attachments?: ({
    [key: string]: unknown;
} | null);
    extra_metadata?: ({
    [key: string]: unknown;
} | null);
    month_value_change?: (number | null);
    month_suspension_resumption?: (number | null);
    month_writeoff_accounting?: (number | null);
    month_writeoff_tax?: (number | null);
    depreciation_months_current_year?: (number | null);
    acquisition_cost_begin_year?: (number | null);
    book_value_begin_year?: (number | null);
    accumulated_depreciation_begin_year?: (number | null);
};

/**
 * Схема за създаване на банкова сметка.
 */
export type BankAccountCreate = {
    /**
     * Номер на сметката
     */
    account_no: string;
    /**
     * IBAN
     */
    iban: string;
    /**
     * BIC/SWIFT код
     */
    bic?: (string | null);
    /**
     * Тип сметка
     */
    account_type?: BankAccountType;
    /**
     * Валута
     */
    currency?: string;
    /**
     * Активна ли е сметката
     */
    is_active?: boolean;
    /**
     * Име на банката
     */
    bank_name: string;
    /**
     * Код на банката
     */
    bank_code?: (string | null);
    /**
     * Клон
     */
    branch_name?: (string | null);
    /**
     * Начално салдо
     */
    initial_balance?: (number | string);
    /**
     * Текущо салдо
     */
    current_balance?: (number | string);
    /**
     * Бележки
     */
    notes?: (string | null);
};

/**
 * Публична схема за банкова сметка.
 */
export type BankAccountPublic = {
    /**
     * Номер на сметката
     */
    account_no: string;
    /**
     * IBAN
     */
    iban: string;
    /**
     * BIC/SWIFT код
     */
    bic?: (string | null);
    /**
     * Тип сметка
     */
    account_type?: BankAccountType;
    /**
     * Валута
     */
    currency?: string;
    /**
     * Активна ли е сметката
     */
    is_active?: boolean;
    /**
     * Име на банката
     */
    bank_name: string;
    /**
     * Код на банката
     */
    bank_code?: (string | null);
    /**
     * Клон
     */
    branch_name?: (string | null);
    /**
     * Начално салдо
     */
    initial_balance?: string;
    /**
     * Текущо салдо
     */
    current_balance?: string;
    /**
     * Бележки
     */
    notes?: (string | null);
    id: string;
    organization_id: string;
    date_created: string;
    date_updated: string;
};

/**
 * Списък банкови сметки.
 */
export type BankAccountsPublic = {
    data: Array<BankAccountPublic>;
    count: number;
};

/**
 * Тип банкова сметка.
 */
export type BankAccountType = 'current' | 'savings' | 'foreign_currency';

/**
 * Схема за актуализация на банкова сметка.
 */
export type BankAccountUpdate = {
    account_no?: (string | null);
    iban?: (string | null);
    bic?: (string | null);
    account_type?: (BankAccountType | null);
    currency?: (string | null);
    is_active?: (boolean | null);
    bank_name?: (string | null);
    bank_code?: (string | null);
    branch_name?: (string | null);
    current_balance?: (number | string | null);
    notes?: (string | null);
};

/**
 * Схема за създаване на банкова транзакция.
 */
export type BankTransactionCreate = {
    /**
     * Дата на осчетоводяване
     */
    booking_date: string;
    /**
     * Вальор
     */
    value_date?: (string | null);
    /**
     * Сума
     */
    amount: (number | string);
    /**
     * Валута
     */
    currency?: string;
    /**
     * Кредитна транзакция (приход)
     */
    is_credit: boolean;
    /**
     * Описание
     */
    description?: (string | null);
    /**
     * Референция
     */
    reference?: (string | null);
    /**
     * Уникален ID на транзакцията
     */
    transaction_id?: (string | null);
    /**
     * Име на контрагент
     */
    counterpart_name?: (string | null);
    /**
     * IBAN на контрагент
     */
    counterpart_iban?: (string | null);
    /**
     * BIC на контрагент
     */
    counterpart_bic?: (string | null);
    /**
     * Обработена ли е
     */
    is_processed?: boolean;
    /**
     * Дата на обработка
     */
    processed_at?: (string | null);
    bank_account_id: string;
    bank_import_id?: (string | null);
    bank_profile_id?: (string | null);
    metadata_json?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Публична схема за банкова транзакция.
 */
export type BankTransactionPublic = {
    /**
     * Дата на осчетоводяване
     */
    booking_date: string;
    /**
     * Вальор
     */
    value_date?: (string | null);
    /**
     * Сума
     */
    amount: string;
    /**
     * Валута
     */
    currency?: string;
    /**
     * Кредитна транзакция (приход)
     */
    is_credit: boolean;
    /**
     * Описание
     */
    description?: (string | null);
    /**
     * Референция
     */
    reference?: (string | null);
    /**
     * Уникален ID на транзакцията
     */
    transaction_id?: (string | null);
    /**
     * Име на контрагент
     */
    counterpart_name?: (string | null);
    /**
     * IBAN на контрагент
     */
    counterpart_iban?: (string | null);
    /**
     * BIC на контрагент
     */
    counterpart_bic?: (string | null);
    /**
     * Обработена ли е
     */
    is_processed?: boolean;
    /**
     * Дата на обработка
     */
    processed_at?: (string | null);
    id: string;
    organization_id: string;
    bank_account_id: string;
    bank_import_id?: (string | null);
    bank_profile_id?: (string | null);
    journal_entry_id?: (string | null);
    date_created: string;
    date_updated: string;
};

/**
 * Списък банкови транзакции.
 */
export type BankTransactionsPublic = {
    data: Array<BankTransactionPublic>;
    count: number;
};

/**
 * Схема за актуализация на банкова транзакция.
 */
export type BankTransactionUpdate = {
    description?: (string | null);
    reference?: (string | null);
    counterpart_name?: (string | null);
    counterpart_iban?: (string | null);
    is_processed?: (boolean | null);
    journal_entry_id?: (string | null);
    metadata_json?: ({
    [key: string]: unknown;
} | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContraagentBankAccountCreate = {
    iban: string;
    bic?: (string | null);
    bank_name?: (string | null);
    account_number?: (string | null);
    currency?: string;
    is_primary?: boolean;
    is_verified?: boolean;
    notes?: (string | null);
    contraagent_id: string;
};

export type ContraagentBankAccountPublic = {
    iban: string;
    bic?: (string | null);
    bank_name?: (string | null);
    account_number?: (string | null);
    currency?: string;
    is_primary?: boolean;
    is_verified?: boolean;
    notes?: (string | null);
    id: string;
    contraagent_id: string;
    date_created: string;
    date_updated: string;
    first_seen_at?: (string | null);
    last_seen_at?: (string | null);
    times_seen: number;
};

export type ContraagentBankAccountsPublic = {
    data: Array<ContraagentBankAccountPublic>;
    count: number;
};

export type ContraagentBankAccountUpdate = {
    iban?: (string | null);
    bic?: (string | null);
    bank_name?: (string | null);
    account_number?: (string | null);
    currency?: (string | null);
    is_primary?: (boolean | null);
    is_verified?: (boolean | null);
    notes?: (string | null);
};

export type ContraagentCreate = {
    name: string;
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    fax?: (string | null);
    is_company?: boolean;
    is_customer?: boolean;
    is_supplier?: boolean;
    is_active?: boolean;
    registration_number?: (string | null);
    vat_number?: (string | null);
    street_name?: (string | null);
    building_number?: (string | null);
    building?: (string | null);
    postal_code?: (string | null);
    city?: (string | null);
    region?: (string | null);
    country?: (string | null);
    additional_address_detail?: (string | null);
    contact_person_title?: (string | null);
    contact_person_first_name?: (string | null);
    contact_person_last_name?: (string | null);
    tax_type?: (string | null);
    tax_authority?: (string | null);
    tax_verification_date?: (string | null);
    self_billing_indicator?: boolean;
    related_party?: boolean;
    related_party_start_date?: (string | null);
    related_party_end_date?: (string | null);
    iban_number?: (string | null);
    bank_account_number?: (string | null);
    bank_sort_code?: (string | null);
    accounting_account_id?: (string | null);
    opening_debit_balance?: (number | string);
    opening_credit_balance?: (number | string);
    closing_debit_balance?: (number | string);
    closing_credit_balance?: (number | string);
    name_latin?: (string | null);
    name_cyrillic?: (string | null);
    notes?: (string | null);
};

export type ContraagentPublic = {
    name: string;
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    fax?: (string | null);
    is_company?: boolean;
    is_customer?: boolean;
    is_supplier?: boolean;
    is_active?: boolean;
    registration_number?: (string | null);
    vat_number?: (string | null);
    street_name?: (string | null);
    building_number?: (string | null);
    building?: (string | null);
    postal_code?: (string | null);
    city?: (string | null);
    region?: (string | null);
    country?: (string | null);
    additional_address_detail?: (string | null);
    contact_person_title?: (string | null);
    contact_person_first_name?: (string | null);
    contact_person_last_name?: (string | null);
    tax_type?: (string | null);
    tax_authority?: (string | null);
    tax_verification_date?: (string | null);
    self_billing_indicator?: boolean;
    related_party?: boolean;
    related_party_start_date?: (string | null);
    related_party_end_date?: (string | null);
    iban_number?: (string | null);
    bank_account_number?: (string | null);
    bank_sort_code?: (string | null);
    accounting_account_id?: (string | null);
    opening_debit_balance?: string;
    opening_credit_balance?: string;
    closing_debit_balance?: string;
    closing_credit_balance?: string;
    name_latin?: (string | null);
    name_cyrillic?: (string | null);
    notes?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
    accounting_account_name?: (string | null);
};

export type ContraagentsPublic = {
    data: Array<ContraagentPublic>;
    count: number;
};

export type ContraagentUpdate = {
    name?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    website?: (string | null);
    fax?: (string | null);
    is_company?: (boolean | null);
    is_customer?: (boolean | null);
    is_supplier?: (boolean | null);
    is_active?: (boolean | null);
    registration_number?: (string | null);
    vat_number?: (string | null);
    street_name?: (string | null);
    building_number?: (string | null);
    building?: (string | null);
    postal_code?: (string | null);
    city?: (string | null);
    region?: (string | null);
    country?: (string | null);
    additional_address_detail?: (string | null);
    contact_person_title?: (string | null);
    contact_person_first_name?: (string | null);
    contact_person_last_name?: (string | null);
    tax_type?: (string | null);
    tax_authority?: (string | null);
    tax_verification_date?: (string | null);
    self_billing_indicator?: (boolean | null);
    related_party?: (boolean | null);
    related_party_start_date?: (string | null);
    related_party_end_date?: (string | null);
    iban_number?: (string | null);
    bank_account_number?: (string | null);
    bank_sort_code?: (string | null);
    accounting_account_id?: (string | null);
    price_list_id?: (string | null);
    opening_debit_balance?: (number | string | null);
    opening_credit_balance?: (number | string | null);
    name_latin?: (string | null);
    name_cyrillic?: (string | null);
    notes?: (string | null);
};

export type CustomerCreate = {
    name: string;
    phone?: (string | null);
    address?: (string | null);
    customer_type_id: string;
};

export type CustomerPublic = {
    name: string;
    phone?: (string | null);
    address?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    customer_type_id: string;
    customer_type_name: string;
    date_created: string;
    date_updated: string;
};

export type CustomersPublic = {
    data: Array<CustomerPublic>;
    count: number;
};

export type CustomerTypeCreate = {
    name: string;
    description?: (string | null);
};

export type CustomerTypePublic = {
    name: string;
    description?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type CustomerTypesPublic = {
    data: Array<CustomerTypePublic>;
    count: number;
};

export type CustomerTypeUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type CustomerUpdate = {
    name?: (string | null);
    phone?: (string | null);
    address?: (string | null);
    customer_type_id?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InvoiceCreate = {
    issue_date: string;
    due_date?: (string | null);
    tax_event_date?: (string | null);
    billing_name: string;
    billing_address?: (string | null);
    billing_vat_number?: (string | null);
    billing_company_id?: (string | null);
    subtotal?: (number | string);
    tax_amount?: (number | string);
    total_amount?: (number | string);
    paid_amount?: (number | string);
    currency?: string;
    payment_method?: (string | null);
    notes?: (string | null);
    payment_terms?: (string | null);
    reference?: (string | null);
    vat_document_type?: string;
    vat_reason?: (string | null);
    oss_country?: (string | null);
    oss_vat_rate?: (number | string | null);
    contact_id: string;
    invoice_no: string;
    invoice_lines: Array<InvoiceLineCreate>;
};

export type InvoiceLineCreate = {
    description: string;
    quantity: (number | string);
    unit_of_measure?: string;
    unit_price: (number | string);
    discount_percent?: (number | string);
    tax_rate?: (number | string);
    product_id?: (string | null);
};

export type InvoiceLinePublic = {
    description: string;
    quantity: string;
    unit_of_measure?: string;
    unit_price: string;
    discount_percent?: string;
    tax_rate?: string;
    id: string;
    subtotal: string;
    tax_amount: string;
    total_amount: string;
    product?: (ItemPublic | null);
};

export type InvoicePublic = {
    issue_date: string;
    due_date?: (string | null);
    tax_event_date?: (string | null);
    billing_name: string;
    billing_address?: (string | null);
    billing_vat_number?: (string | null);
    billing_company_id?: (string | null);
    subtotal?: string;
    tax_amount?: string;
    total_amount?: string;
    paid_amount?: string;
    currency?: string;
    payment_method?: (string | null);
    notes?: (string | null);
    payment_terms?: (string | null);
    reference?: (string | null);
    vat_document_type?: string;
    vat_reason?: (string | null);
    oss_country?: (string | null);
    oss_vat_rate?: (string | null);
    id: string;
    invoice_no: string;
    status: InvoiceStatus;
    customer: CustomerPublic;
    invoice_lines: Array<InvoiceLinePublic>;
};

export type InvoicesPublic = {
    data: Array<InvoicePublic>;
    count: number;
};

export type InvoiceStatus = 'draft' | 'issued' | 'paid' | 'partially_paid' | 'overdue' | 'cancelled';

export type ItemCategoriesPublic = {
    data: Array<ItemCategoryPublic>;
    count: number;
};

export type ItemCategoryCreate = {
    name: string;
    description?: (string | null);
};

export type ItemCategoryPublic = {
    name: string;
    description?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type ItemCategoryUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
    price_purchase?: (number | null);
    price_sell?: (number | null);
    stock_minimum?: number;
    is_active?: boolean;
    item_category_id: string;
    item_unit_id: string;
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    price_purchase?: (number | null);
    price_sell?: (number | null);
    stock_minimum?: number;
    is_active?: boolean;
    id: string;
    stock: number;
    organization_id: string;
    created_by_id: string;
    item_category_id: string;
    item_category_name: string;
    item_unit_id: string;
    item_unit_name: string;
    date_created: string;
    date_updated: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUnitCreate = {
    name: string;
    description?: (string | null);
};

export type ItemUnitPublic = {
    name: string;
    description?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type ItemUnitsPublic = {
    data: Array<ItemUnitPublic>;
    count: number;
};

export type ItemUnitUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    price_purchase?: (number | null);
    price_sell?: (number | null);
    stock_minimum?: number;
    is_active?: boolean;
    item_category_id?: (string | null);
    item_unit_id?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationCreate = {
    name: string;
    slug: string;
    is_active?: boolean;
    region_code?: (string | null);
    default_currency?: (string | null);
    tax_basis?: (string | null);
    accounts_receivable_account_id?: (string | null);
    sales_revenue_account_id?: (string | null);
    vat_payable_account_id?: (string | null);
    inventory_account_id?: (string | null);
    accounts_payable_account_id?: (string | null);
    vat_deductible_account_id?: (string | null);
    cash_account_id?: (string | null);
};

export type OrganizationMemberCreate = {
    user_id: string;
    role?: OrganizationRole;
};

export type OrganizationMemberPublic = {
    role?: OrganizationRole;
    is_active?: boolean;
    id: string;
    user_id: string;
    organization_id: string;
    date_joined: string;
    date_updated: string;
};

export type OrganizationMembersPublic = {
    data: Array<OrganizationMemberPublic>;
    count: number;
};

export type OrganizationMemberUpdate = {
    role?: (OrganizationRole | null);
    is_active?: (boolean | null);
};

export type OrganizationPublic = {
    name: string;
    slug: string;
    is_active?: boolean;
    region_code?: (string | null);
    default_currency?: (string | null);
    tax_basis?: (string | null);
    accounts_receivable_account_id?: (string | null);
    sales_revenue_account_id?: (string | null);
    vat_payable_account_id?: (string | null);
    inventory_account_id?: (string | null);
    accounts_payable_account_id?: (string | null);
    vat_deductible_account_id?: (string | null);
    cash_account_id?: (string | null);
    id: string;
    date_created: string;
    date_updated: string;
};

/**
 * Роли в организацията с йерархия: ADMIN > MANAGER > MEMBER
 */
export type OrganizationRole = 'admin' | 'manager' | 'member';

export type OrganizationsPublic = {
    data: Array<OrganizationPublic>;
    count: number;
};

export type OrganizationUpdate = {
    name?: (string | null);
    slug?: (string | null);
    is_active?: (boolean | null);
    region_code?: (string | null);
    default_currency?: (string | null);
    tax_basis?: (string | null);
    accounts_receivable_account_id?: (string | null);
    sales_revenue_account_id?: (string | null);
    vat_payable_account_id?: (string | null);
    inventory_account_id?: (string | null);
    accounts_payable_account_id?: (string | null);
    vat_deductible_account_id?: (string | null);
    cash_account_id?: (string | null);
};

export type PaymentCreate = {
    date_payment: string;
    amount?: number;
    method: string;
    reference_id?: (string | null);
    description?: (string | null);
    transaction_type?: (string | null);
    transaction_id?: (string | null);
    subject_type?: (string | null);
    subject_id?: (string | null);
    is_reversal?: boolean;
    is_reversal_payment_id?: (string | null);
};

export type PaymentPublic = {
    date_payment: string;
    amount?: number;
    method: string;
    reference_id?: (string | null);
    description?: (string | null);
    transaction_type?: (string | null);
    transaction_id?: (string | null);
    subject_type?: (string | null);
    subject_id?: (string | null);
    is_reversal?: boolean;
    is_reversal_payment_id?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    account_id: string;
    date_created: string;
};

export type PaymentsPublic = {
    data: Array<PaymentPublic>;
    count: number;
};

export type PermissionCreate = {
    name: string;
    description?: (string | null);
};

export type PermissionPublic = {
    name: string;
    description?: (string | null);
    id: string;
    date_created: string;
    date_updated: string;
    organization_id: string;
    created_by_id: string;
    editor_id: string;
};

export type PermissionsPublic = {
    data: Array<PermissionPublic>;
    count: number;
};

export type PermissionUpdate = {
    name: (string | null);
    description?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PurchaseCreate = {
    date_purchase: string;
    amount?: number;
    description?: (string | null);
    supplier_id: string;
    store_id: string;
};

export type PurchasePublic = {
    date_purchase: string;
    amount?: number;
    description?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    supplier_id: string;
    supplier_name: string;
    store_id: string;
    store_name: string;
    date_created: string;
    date_updated: string;
};

export type PurchasesPublic = {
    data: Array<PurchasePublic>;
    count: number;
};

export type PurchaseUpdate = {
    date_purchase?: (string | null);
    amount?: (number | null);
    description?: (string | null);
    supplier_id?: (string | null);
    store_id?: (string | null);
};

export type SaleCreate = {
    date_sale: string;
    amount?: number;
    description?: (string | null);
    customer_id: string;
    store_id: string;
};

export type SalePublic = {
    date_sale: string;
    amount?: number;
    description?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    customer_id: string;
    customer_name: string;
    store_id: string;
    store_name: string;
    date_created: string;
    date_updated: string;
};

export type SalesPublic = {
    data: Array<SalePublic>;
    count: number;
};

export type SaleUpdate = {
    date_sale?: (string | null);
    amount?: (number | null);
    description?: (string | null);
    customer_id?: (string | null);
    store_id?: (string | null);
};

export type StockLevelCreate = {
    quantity?: number;
    item_id: string;
    store_id: string;
};

export type StockLevelPublic = {
    quantity?: number;
    id: string;
    organization_id: string;
    created_by_id: string;
    item_id: string;
    store_id: string;
    date_created: string;
    date_updated: string;
};

export type StockLevelsPublic = {
    data: Array<StockLevelPublic>;
    count: number;
};

export type StockLevelUpdate = {
    quantity?: number;
};

export type StoreCreate = {
    name: string;
    address?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type StorePublic = {
    name: string;
    address?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type StoresPublic = {
    data: Array<StorePublic>;
    count: number;
};

export type StoreUpdate = {
    name?: (string | null);
    address?: (string | null);
    latitude?: (number | null);
    longitude?: (number | null);
};

export type SupplierCreate = {
    name: string;
    phone?: (string | null);
    address?: (string | null);
};

export type SupplierPublic = {
    name: string;
    phone?: (string | null);
    address?: (string | null);
    id: string;
    organization_id: string;
    created_by_id: string;
    date_created: string;
    date_updated: string;
};

export type SuppliersPublic = {
    data: Array<SupplierPublic>;
    count: number;
};

export type SupplierUpdate = {
    name?: (string | null);
    phone?: (string | null);
    address?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    current_organization_id: (string | null);
    date_created: string;
    date_updated: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AccountsReadAccountsData = {
    limit?: number;
    skip?: number;
};

export type AccountsReadAccountsResponse = (AccountsPublic);

export type AccountsCreateAccountData = {
    requestBody: AccountCreate;
};

export type AccountsCreateAccountResponse = (AccountPublic);

export type AccountsReadAccountData = {
    id: string;
};

export type AccountsReadAccountResponse = (AccountPublic);

export type AccountsUpdateAccountData = {
    id: string;
    requestBody: AccountUpdate;
};

export type AccountsUpdateAccountResponse = (AccountPublic);

export type AccountsDeleteAccountData = {
    id: string;
};

export type AccountsDeleteAccountResponse = (Message);

export type AssetsListAssetsData = {
    category?: (string | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
    status?: (string | null);
};

export type AssetsListAssetsResponse = (AssetsPublic);

export type AssetsCreateAssetData = {
    requestBody: AssetCreate;
};

export type AssetsCreateAssetResponse = (AssetPublic);

export type AssetsGetAssetData = {
    assetId: string;
};

export type AssetsGetAssetResponse = (AssetPublic);

export type AssetsUpdateAssetData = {
    assetId: string;
    requestBody: AssetUpdate;
};

export type AssetsUpdateAssetResponse = (AssetPublic);

export type AssetsDeleteAssetData = {
    assetId: string;
};

export type AssetsDeleteAssetResponse = (unknown);

export type AssetsGetAssetStatisticsResponse = ({
    [key: string]: unknown;
});

export type BankAccountsListBankAccountsData = {
    isActive?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type BankAccountsListBankAccountsResponse = (BankAccountsPublic);

export type BankAccountsCreateBankAccountData = {
    requestBody: BankAccountCreate;
};

export type BankAccountsCreateBankAccountResponse = (BankAccountPublic);

export type BankAccountsGetBankAccountData = {
    accountId: string;
};

export type BankAccountsGetBankAccountResponse = (BankAccountPublic);

export type BankAccountsUpdateBankAccountData = {
    accountId: string;
    requestBody: BankAccountUpdate;
};

export type BankAccountsUpdateBankAccountResponse = (BankAccountPublic);

export type BankAccountsDeleteBankAccountData = {
    accountId: string;
};

export type BankAccountsDeleteBankAccountResponse = (unknown);

export type BankTransactionsListBankTransactionsData = {
    bankAccountId?: (string | null);
    isCredit?: (boolean | null);
    isProcessed?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type BankTransactionsListBankTransactionsResponse = (BankTransactionsPublic);

export type BankTransactionsCreateBankTransactionData = {
    requestBody: BankTransactionCreate;
};

export type BankTransactionsCreateBankTransactionResponse = (BankTransactionPublic);

export type BankTransactionsGetBankTransactionData = {
    transactionId: string;
};

export type BankTransactionsGetBankTransactionResponse = (BankTransactionPublic);

export type BankTransactionsUpdateBankTransactionData = {
    requestBody: BankTransactionUpdate;
    transactionId: string;
};

export type BankTransactionsUpdateBankTransactionResponse = (BankTransactionPublic);

export type BankTransactionsDeleteBankTransactionData = {
    transactionId: string;
};

export type BankTransactionsDeleteBankTransactionResponse = (unknown);

export type BankTransactionsProcessBankTransactionData = {
    journalEntryId?: (string | null);
    transactionId: string;
};

export type BankTransactionsProcessBankTransactionResponse = (BankTransactionPublic);

export type ContraagentsReadContraagentsData = {
    /**
     * Filter by active status
     */
    isActive?: (boolean | null);
    /**
     * Filter by customer status
     */
    isCustomer?: (boolean | null);
    /**
     * Filter by supplier status
     */
    isSupplier?: (boolean | null);
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ContraagentsReadContraagentsResponse = (ContraagentsPublic);

export type ContraagentsCreateContraagentData = {
    requestBody: ContraagentCreate;
    /**
     * Validate VAT number using VIES
     */
    validateVat?: boolean;
};

export type ContraagentsCreateContraagentResponse = (ContraagentPublic);

export type ContraagentsReadContraagentData = {
    id: string;
};

export type ContraagentsReadContraagentResponse = (ContraagentPublic);

export type ContraagentsUpdateContraagentData = {
    id: string;
    requestBody: ContraagentUpdate;
    /**
     * Validate VAT number using VIES
     */
    validateVat?: boolean;
};

export type ContraagentsUpdateContraagentResponse = (ContraagentPublic);

export type ContraagentsDeleteContraagentData = {
    id: string;
};

export type ContraagentsDeleteContraagentResponse = (Message);

export type ContraagentsValidateVatNumberData = {
    /**
     * VAT number to validate
     */
    vatNumber: string;
};

export type ContraagentsValidateVatNumberResponse = (unknown);

export type ContraagentsSetOpeningBalanceData = {
    /**
     * Opening credit balance
     */
    creditBalance?: (number | string);
    /**
     * Opening debit balance
     */
    debitBalance?: (number | string);
    /**
     * Description for journal entry
     */
    description?: (string | null);
    id: string;
};

export type ContraagentsSetOpeningBalanceResponse = (unknown);

export type ContraagentsRemoveOpeningBalanceData = {
    id: string;
};

export type ContraagentsRemoveOpeningBalanceResponse = (unknown);

export type ContraagentsGetOpeningBalancesSummaryResponse = (unknown);

export type ContraagentsReadContraagentBankAccountsData = {
    id: string;
};

export type ContraagentsReadContraagentBankAccountsResponse = (ContraagentBankAccountsPublic);

export type ContraagentsCreateContraagentBankAccountData = {
    id: string;
    requestBody: ContraagentBankAccountCreate;
};

export type ContraagentsCreateContraagentBankAccountResponse = (ContraagentBankAccountPublic);

export type ContraagentsUpdateContraagentBankAccountData = {
    bankAccountId: string;
    requestBody: ContraagentBankAccountUpdate;
};

export type ContraagentsUpdateContraagentBankAccountResponse = (ContraagentBankAccountPublic);

export type ContraagentsDeleteContraagentBankAccountData = {
    bankAccountId: string;
};

export type ContraagentsDeleteContraagentBankAccountResponse = (Message);

export type CustomersReadCustomersData = {
    limit?: number;
    skip?: number;
};

export type CustomersReadCustomersResponse = (CustomersPublic);

export type CustomersCreateCustomerData = {
    requestBody: CustomerCreate;
};

export type CustomersCreateCustomerResponse = (CustomerPublic);

export type CustomersReadCustomerData = {
    id: string;
};

export type CustomersReadCustomerResponse = (CustomerPublic);

export type CustomersUpdateCustomerData = {
    id: string;
    requestBody: CustomerUpdate;
};

export type CustomersUpdateCustomerResponse = (CustomerPublic);

export type CustomersDeleteCustomerData = {
    id: string;
};

export type CustomersDeleteCustomerResponse = (Message);

export type CustomerTypesReadCustomerTypesData = {
    limit?: number;
    skip?: number;
};

export type CustomerTypesReadCustomerTypesResponse = (CustomerTypesPublic);

export type CustomerTypesCreateCustomerTypeData = {
    requestBody: CustomerTypeCreate;
};

export type CustomerTypesCreateCustomerTypeResponse = (CustomerTypePublic);

export type CustomerTypesReadCustomerTypeData = {
    id: string;
};

export type CustomerTypesReadCustomerTypeResponse = (CustomerTypePublic);

export type CustomerTypesUpdateCustomerTypeData = {
    id: string;
    requestBody: CustomerTypeUpdate;
};

export type CustomerTypesUpdateCustomerTypeResponse = (CustomerTypePublic);

export type CustomerTypesDeleteCustomerTypeData = {
    id: string;
};

export type CustomerTypesDeleteCustomerTypeResponse = (Message);

export type InvoicesReadInvoicesData = {
    limit?: number;
    skip?: number;
};

export type InvoicesReadInvoicesResponse = (InvoicesPublic);

export type InvoicesCreateInvoiceData = {
    requestBody: InvoiceCreate;
};

export type InvoicesCreateInvoiceResponse = (InvoicePublic);

export type ItemCategoriesReadItemCategoriesData = {
    limit?: number;
    skip?: number;
};

export type ItemCategoriesReadItemCategoriesResponse = (ItemCategoriesPublic);

export type ItemCategoriesCreateItemCategoryData = {
    requestBody: ItemCategoryCreate;
};

export type ItemCategoriesCreateItemCategoryResponse = (ItemCategoryPublic);

export type ItemCategoriesReadItemCategoryData = {
    id: string;
};

export type ItemCategoriesReadItemCategoryResponse = (ItemCategoryPublic);

export type ItemCategoriesUpdateItemCategoryData = {
    id: string;
    requestBody: ItemCategoryUpdate;
};

export type ItemCategoriesUpdateItemCategoryResponse = (ItemCategoryPublic);

export type ItemCategoriesDeleteItemCategoryData = {
    id: string;
};

export type ItemCategoriesDeleteItemCategoryResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type ItemsReadLowStockItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadLowStockItemsResponse = (ItemsPublic);

export type ItemsActivateItemData = {
    id: string;
};

export type ItemsActivateItemResponse = (ItemPublic);

export type ItemsDeactivateItemData = {
    id: string;
};

export type ItemsDeactivateItemResponse = (ItemPublic);

export type ItemUnitsReadItemUnitsData = {
    limit?: number;
    skip?: number;
};

export type ItemUnitsReadItemUnitsResponse = (ItemUnitsPublic);

export type ItemUnitsCreateItemUnitData = {
    requestBody: ItemUnitCreate;
};

export type ItemUnitsCreateItemUnitResponse = (ItemUnitPublic);

export type ItemUnitsReadItemUnitData = {
    id: string;
};

export type ItemUnitsReadItemUnitResponse = (ItemUnitPublic);

export type ItemUnitsUpdateItemUnitData = {
    id: string;
    requestBody: ItemUnitUpdate;
};

export type ItemUnitsUpdateItemUnitResponse = (ItemUnitPublic);

export type ItemUnitsDeleteItemUnitData = {
    id: string;
};

export type ItemUnitsDeleteItemUnitResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OrganizationsReadOrganizationsData = {
    limit?: number;
    skip?: number;
};

export type OrganizationsReadOrganizationsResponse = (OrganizationsPublic);

export type OrganizationsCreateOrganizationData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadCurrentOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadOrganizationData = {
    id: string;
};

export type OrganizationsReadOrganizationResponse = (OrganizationPublic);

export type OrganizationsUpdateOrganizationData = {
    id: string;
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateOrganizationResponse = (OrganizationPublic);

export type OrganizationsDeleteOrganizationData = {
    id: string;
};

export type OrganizationsDeleteOrganizationResponse = (Message);

export type OrganizationsSwitchOrganizationData = {
    id: string;
};

export type OrganizationsSwitchOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadOrganizationMembersData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type OrganizationsReadOrganizationMembersResponse = (OrganizationMembersPublic);

export type OrganizationsAddOrganizationMemberData = {
    id: string;
    requestBody: OrganizationMemberCreate;
};

export type OrganizationsAddOrganizationMemberResponse = (OrganizationMemberPublic);

export type OrganizationsUpdateOrganizationMemberData = {
    id: string;
    requestBody: OrganizationMemberUpdate;
    userId: string;
};

export type OrganizationsUpdateOrganizationMemberResponse = (OrganizationMemberPublic);

export type OrganizationsRemoveOrganizationMemberData = {
    id: string;
    userId: string;
};

export type OrganizationsRemoveOrganizationMemberResponse = (Message);

export type PaymentsReadPaymentsData = {
    limit?: number;
    skip?: number;
};

export type PaymentsReadPaymentsResponse = (PaymentsPublic);

export type PaymentsCreatePaymentData = {
    requestBody: PaymentCreate;
};

export type PaymentsCreatePaymentResponse = (PaymentPublic);

export type PermissionsReadPermissionsData = {
    limit?: number;
    skip?: number;
};

export type PermissionsReadPermissionsResponse = (PermissionsPublic);

export type PermissionsCreatePermissionData = {
    requestBody: PermissionCreate;
};

export type PermissionsCreatePermissionResponse = (PermissionPublic);

export type PermissionsReadPermissionData = {
    id: string;
};

export type PermissionsReadPermissionResponse = (PermissionPublic);

export type PermissionsUpdatePermissionData = {
    id: string;
    requestBody: PermissionUpdate;
};

export type PermissionsUpdatePermissionResponse = (PermissionPublic);

export type PermissionsDeletePermissionData = {
    id: string;
};

export type PermissionsDeletePermissionResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PurchasesReadPurchasesData = {
    limit?: number;
    skip?: number;
};

export type PurchasesReadPurchasesResponse = (PurchasesPublic);

export type PurchasesCreatePurchaseData = {
    requestBody: PurchaseCreate;
};

export type PurchasesCreatePurchaseResponse = (PurchasePublic);

export type PurchasesReadPurchaseData = {
    id: string;
};

export type PurchasesReadPurchaseResponse = (PurchasePublic);

export type PurchasesUpdatePurchaseData = {
    id: string;
    requestBody: PurchaseUpdate;
};

export type PurchasesUpdatePurchaseResponse = (PurchasePublic);

export type PurchasesDeletePurchaseData = {
    id: string;
};

export type PurchasesDeletePurchaseResponse = (Message);

export type SaftGenerateSaftData = {
    month?: (number | null);
    reportType: string;
    year: number;
};

export type SaftGenerateSaftResponse = (unknown);

export type SalesReadSalesData = {
    limit?: number;
    skip?: number;
};

export type SalesReadSalesResponse = (SalesPublic);

export type SalesCreateSaleData = {
    requestBody: SaleCreate;
};

export type SalesCreateSaleResponse = (SalePublic);

export type SalesReadSaleData = {
    id: string;
};

export type SalesReadSaleResponse = (SalePublic);

export type SalesUpdateSaleData = {
    id: string;
    requestBody: SaleUpdate;
};

export type SalesUpdateSaleResponse = (SalePublic);

export type SalesDeleteSaleData = {
    id: string;
};

export type SalesDeleteSaleResponse = (Message);

export type StockLevelsReadStockLevelsData = {
    limit?: number;
    skip?: number;
};

export type StockLevelsReadStockLevelsResponse = (StockLevelsPublic);

export type StockLevelsCreateStockLevelData = {
    requestBody: StockLevelCreate;
};

export type StockLevelsCreateStockLevelResponse = (StockLevelPublic);

export type StockLevelsReadStockLevelData = {
    id: string;
};

export type StockLevelsReadStockLevelResponse = (StockLevelPublic);

export type StockLevelsUpdateStockLevelData = {
    id: string;
    requestBody: StockLevelUpdate;
};

export type StockLevelsUpdateStockLevelResponse = (StockLevelPublic);

export type StockLevelsDeleteStockLevelData = {
    id: string;
};

export type StockLevelsDeleteStockLevelResponse = (Message);

export type StoresReadStoresData = {
    limit?: number;
    skip?: number;
};

export type StoresReadStoresResponse = (StoresPublic);

export type StoresCreateStoreData = {
    requestBody: StoreCreate;
};

export type StoresCreateStoreResponse = (StorePublic);

export type StoresReadStoreData = {
    id: string;
};

export type StoresReadStoreResponse = (StorePublic);

export type StoresUpdateStoreData = {
    id: string;
    requestBody: StoreUpdate;
};

export type StoresUpdateStoreResponse = (StorePublic);

export type StoresDeleteStoreData = {
    id: string;
};

export type StoresDeleteStoreResponse = (Message);

export type SuppliersReadSuppliersData = {
    limit?: number;
    skip?: number;
};

export type SuppliersReadSuppliersResponse = (SuppliersPublic);

export type SuppliersCreateSupplierData = {
    requestBody: SupplierCreate;
};

export type SuppliersCreateSupplierResponse = (SupplierPublic);

export type SuppliersReadSupplierData = {
    id: string;
};

export type SuppliersReadSupplierResponse = (SupplierPublic);

export type SuppliersUpdateSupplierData = {
    id: string;
    requestBody: SupplierUpdate;
};

export type SuppliersUpdateSupplierResponse = (SupplierPublic);

export type SuppliersDeleteSupplierData = {
    id: string;
};

export type SuppliersDeleteSupplierResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadSpecialData = {
    limit?: number;
    skip?: number;
};

export type UsersReadSpecialResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);