"""add saft nomenclature tables

Revision ID: 29b8c3a1e8c7
Revises: 
Create Date: 2025-12-14 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29b8c3a1e8c7'
down_revision = 'add_multi_tenant'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saft_iban_formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('bank_code_format', sa.String(), nullable=True),
    sa.Column('iban_fields', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_iban_formats_country_code'), 'saft_iban_formats', ['country_code'], unique=True)

    op.create_table('saft_invoice_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name_bg', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_invoice_types_code'), 'saft_invoice_types', ['code'], unique=True)

    op.create_table('saft_payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method_code', sa.String(length=2), nullable=False),
    sa.Column('payment_mechanism_code', sa.String(length=2), nullable=False),
    sa.Column('description_bg', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_payment_methods_payment_mechanism_code'), 'saft_payment_methods', ['payment_mechanism_code'], unique=False)
    op.create_index(op.f('ix_saft_payment_methods_payment_method_code'), 'saft_payment_methods', ['payment_method_code'], unique=False)
    op.create_unique_constraint('uq_saft_payment_methods_payment_method_mechanism', 'saft_payment_methods', ['payment_method_code', 'payment_mechanism_code'])

    op.create_table('saft_movement_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name_bg', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_movement_types_code'), 'saft_movement_types', ['code'], unique=True)

    op.create_table('saft_asset_movement_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name_bg', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_asset_movement_types_code'), 'saft_asset_movement_types', ['code'], unique=True)

    op.create_table('saft_vat_tax_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_bg', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_vat_tax_types_code'), 'saft_vat_tax_types', ['code'], unique=True)

    op.create_table('saft_inventory_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name_bg', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_inventory_types_code'), 'saft_inventory_types', ['code'], unique=True)

    op.create_table('saft_tax_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_bg', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('tax_type', sa.String(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_tax_codes_code'), 'saft_tax_codes', ['code'], unique=True)

    op.create_table('saft_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('code3', sa.String(length=3), nullable=True),
    sa.Column('numeric_code', sa.String(length=3), nullable=True),
    sa.Column('name_bg', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_official', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_countries_code'), 'saft_countries', ['code'], unique=True)
    op.create_index(op.f('ix_saft_countries_code3'), 'saft_countries', ['code3'], unique=True)

    op.create_table('saft_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('numeric_code', sa.String(length=3), nullable=True),
    sa.Column('name_bg', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_currencies_code'), 'saft_currencies', ['code'], unique=True)

    op.create_table('saft_bg_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name_bg', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_bg_regions_code'), 'saft_bg_regions', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saft_bg_regions_code'), table_name='saft_bg_regions')
    op.drop_table('saft_bg_regions')
    op.drop_index(op.f('ix_saft_currencies_code'), table_name='saft_currencies')
    op.drop_table('saft_currencies')
    op.drop_index(op.f('ix_saft_countries_code3'), table_name='saft_countries')
    op.drop_index(op.f('ix_saft_countries_code'), table_name='saft_countries')
    op.drop_table('saft_countries')
    op.drop_index(op.f('ix_saft_tax_codes_code'), table_name='saft_tax_codes')
    op.drop_table('saft_tax_codes')
    op.drop_index(op.f('ix_saft_inventory_types_code'), table_name='saft_inventory_types')
    op.drop_table('saft_inventory_types')
    op.drop_index(op.f('ix_saft_vat_tax_types_code'), table_name='saft_vat_tax_types')
    op.drop_table('saft_vat_tax_types')
    op.drop_index(op.f('ix_saft_asset_movement_types_code'), table_name='saft_asset_movement_types')
    op.drop_table('saft_asset_movement_types')
    op.drop_index(op.f('ix_saft_movement_types_code'), table_name='saft_movement_types')
    op.drop_table('saft_movement_types')
    op.drop_constraint('uq_saft_payment_methods_payment_method_mechanism', 'saft_payment_methods', type_='unique')
    op.drop_index(op.f('ix_saft_payment_methods_payment_method_code'), table_name='saft_payment_methods')
    op.drop_index(op.f('ix_saft_payment_methods_payment_mechanism_code'), table_name='saft_payment_methods')
    op.drop_table('saft_payment_methods')
    op.drop_index(op.f('ix_saft_invoice_types_code'), table_name='saft_invoice_types')
    op.drop_table('saft_invoice_types')
    op.drop_index(op.f('ix_saft_iban_formats_country_code'), table_name='saft_iban_formats')
    op.drop_table('saft_iban_formats')
    # ### end Alembic commands ###
