"""add asset_transactions and saft fields to assets

Revision ID: 4e5f3f4e4e4e
Revises: 3a3d9f3e3d3b
Create Date: 2025-12-14 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5f3f4e4e4e'
down_revision = '3a3d9f3e3d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('acquisition_cost_change', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('book_value_after', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('supplier_customer_id', sa.Integer(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('saft_transaction_id', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['supplier_customer_id'], ['customer.id'], ), # Assuming customer can be a supplier too for now
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_transaction_asset_id'), 'asset_transaction', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_transaction_organization_id'), 'asset_transaction', ['organization_id'], unique=False)
    op.create_index(op.f('ix_asset_transaction_saft_transaction_id'), 'asset_transaction', ['saft_transaction_id'], unique=False)
    op.create_index(op.f('ix_asset_transaction_transaction_date'), 'asset_transaction', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_asset_transaction_transaction_type'), 'asset_transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_asset_transaction_year_month'), 'asset_transaction', ['year', 'month'], unique=False)

    op.add_column('asset', sa.Column('month_value_change', sa.Integer(), nullable=True))
    op.add_column('asset', sa.Column('month_suspension_resumption', sa.Integer(), nullable=True))
    op.add_column('asset', sa.Column('month_writeoff_accounting', sa.Integer(), nullable=True))
    op.add_column('asset', sa.Column('month_writeoff_tax', sa.Integer(), nullable=True))
    op.add_column('asset', sa.Column('depreciation_months_current_year', sa.Integer(), nullable=True))
    op.add_column('asset', sa.Column('acquisition_cost_begin_year', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('asset', sa.Column('book_value_begin_year', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('asset', sa.Column('accumulated_depreciation_begin_year', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('asset', sa.Column('startup_date', sa.Date(), nullable=True))
    op.add_column('asset', sa.Column('purchase_order_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_asset_month_value_change'), 'asset', ['month_value_change'], unique=False)
    op.create_index(op.f('ix_asset_month_writeoff_accounting'), 'asset', ['month_writeoff_accounting'], unique=False)
    op.create_index(op.f('ix_asset_startup_date'), 'asset', ['startup_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_startup_date'), table_name='asset')
    op.drop_index(op.f('ix_asset_month_writeoff_accounting'), table_name='asset')
    op.drop_index(op.f('ix_asset_month_value_change'), table_name='asset')
    op.drop_column('asset', 'purchase_order_date')
    op.drop_column('asset', 'startup_date')
    op.drop_column('asset', 'accumulated_depreciation_begin_year')
    op.drop_column('asset', 'book_value_begin_year')
    op.drop_column('asset', 'acquisition_cost_begin_year')
    op.drop_column('asset', 'depreciation_months_current_year')
    op.drop_column('asset', 'month_writeoff_tax')
    op.drop_column('asset', 'month_writeoff_accounting')
    op.drop_column('asset', 'month_suspension_resumption')
    op.drop_column('asset', 'month_value_change')

    op.drop_index(op.f('ix_asset_transaction_year_month'), table_name='asset_transaction')
    op.drop_index(op.f('ix_asset_transaction_transaction_type'), table_name='asset_transaction')
    op.drop_index(op.f('ix_asset_transaction_transaction_date'), table_name='asset_transaction')
    op.drop_index(op.f('ix_asset_transaction_saft_transaction_id'), table_name='asset_transaction')
    op.drop_index(op.f('ix_asset_transaction_organization_id'), table_name='asset_transaction')
    op.drop_index(op.f('ix_asset_transaction_asset_id'), table_name='asset_transaction')
    op.drop_table('asset_transaction')
    # ### end Alembic commands ###
