"""add currency and exchange rate tables

Revision ID: 581f3a2b4c5d
Revises: 4736280a5744
Create Date: 2025-12-14 15:19:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "581f3a2b4c5d"
down_revision = "merge_heads"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create currencies table
    op.create_table(
        "currencies",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("name_bg", sa.String(length=100), nullable=True),
        sa.Column("symbol", sa.String(length=10), nullable=True),
        sa.Column("decimal_places", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_base_currency", sa.Boolean(), nullable=True),
        sa.Column("bnb_code", sa.String(length=3), nullable=True),
        sa.Column("ecb_code", sa.String(length=3), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currencies_code"), "currencies", ["code"], unique=True)
    op.create_index(
        "ix_currencies_is_active", "currencies", ["is_active"], unique=False
    )
    op.create_index(
        "ix_currencies_is_base_currency",
        "currencies",
        ["is_base_currency"],
        unique=False,
    )

    # Create exchange_rates table
    op.create_table(
        "exchange_rates",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("from_currency_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("to_currency_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("rate", sa.Numeric(precision=15, scale=6), nullable=False),
        sa.Column("reverse_rate", sa.Numeric(precision=15, scale=6), nullable=True),
        sa.Column("valid_date", sa.Date(), nullable=False),
        sa.Column("rate_source", sa.String(length=20), nullable=True),
        sa.Column("bnb_rate_id", sa.String(length=50), nullable=True),
        sa.Column("ecb_rate_id", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_currency_id"],
            ["currencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_currency_id",
            "to_currency_id",
            "valid_date",
            name="uq_exchange_rate_pair_date",
        ),
        sa.CheckConstraint("rate > 0", name="ck_exchange_rate_positive"),
        sa.CheckConstraint(
            "rate_source IN ('manual', 'bnb', 'ecb', 'api')",
            name="ck_exchange_rate_source",
        ),
    )
    op.create_index(
        "ix_exchange_rate_valid_date", "exchange_rates", ["valid_date"], unique=False
    )
    op.create_index(
        "ix_exchange_rate_rate_source", "exchange_rates", ["rate_source"], unique=False
    )
    op.create_index(
        "ix_exchange_rate_is_active", "exchange_rates", ["is_active"], unique=False
    )
    op.create_index(
        "ix_exchange_rate_bnb_rate_id", "exchange_rates", ["bnb_rate_id"], unique=False
    )

    # Insert initial currencies (without user references for now)
    op.execute("""
        INSERT INTO currencies (id, code, name, name_bg, symbol, decimal_places, is_active, is_base_currency) VALUES
        (gen_random_uuid(), 'BGN', 'Bulgarian Lev', 'Български лев', 'лв.', 2, true, true),
        (gen_random_uuid(), 'EUR', 'Euro', 'Евро', '€', 2, true, false),
        (gen_random_uuid(), 'USD', 'US Dollar', 'Американски долар', '$', 2, true, false)
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exchange_rates")
    op.drop_index(op.f("ix_currencies_code"), table_name="currencies")
    op.drop_index("ix_currencies_is_base_currency", table_name="currencies")
    op.drop_index("ix_currencies_is_active", table_name="currencies")
    op.drop_table("currencies")
    # ### end Alembic commands ###
