"""create saft_nc8_taric_codes table

Revision ID: 5f0f3f5f5f5f
Revises: 4e5f3f4e4e4e
Create Date: 2025-12-14 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0f3f5f5f5f'
down_revision = '4e5f3f4e4e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saft_nc8_taric_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description_bg', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saft_nc8_taric_codes_organization_id_code'), 'saft_nc8_taric_codes', ['organization_id', 'code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saft_nc8_taric_codes_organization_id_code'), table_name='saft_nc8_taric_codes')
    op.drop_table('saft_nc8_taric_codes')
    # ### end Alembic commands ###
