"""add year to saft_nc8_taric_codes

Revision ID: 6a1b1a1b1a1b
Revises: 5f0f3f5f5f5f
Create Date: 2025-12-14 16:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1b1a1b1a1b'
down_revision = '5f0f3f5f5f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saft_nc8_taric_codes', sa.Column('year', sa.Integer(), nullable=False, server_default='2026'))
    op.add_column('saft_nc8_taric_codes', sa.Column('primary_unit', sa.String(), nullable=True))
    op.add_column('saft_nc8_taric_codes', sa.Column('secondary_unit', sa.String(), nullable=True))
    op.drop_index('ix_saft_nc8_taric_codes_organization_id_code', table_name='saft_nc8_taric_codes')
    op.create_index('ix_saft_nc8_taric_codes_organization_id_code_year', 'saft_nc8_taric_codes', ['organization_id', 'code', 'year'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saft_nc8_taric_codes_organization_id_code_year', table_name='saft_nc8_taric_codes')
    op.create_index('ix_saft_nc8_taric_codes_organization_id_code', 'saft_nc8_taric_codes', ['organization_id', 'code'], unique=True)
    op.drop_column('saft_nc8_taric_codes', 'secondary_unit')
    op.drop_column('saft_nc8_taric_codes', 'primary_unit')
    op.drop_column('saft_nc8_taric_codes', 'year')
    # ### end Alembic commands ###
