"""Add Invoice and InvoiceLine tables

Revision ID: 77539d0fc467
Revises: 3fb3aa595a1d
Create Date: 2025-12-14 06:17:19.924524

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77539d0fc467'
down_revision = '3fb3aa595a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.add_column('permission', sa.Column('editor_id', sa.Uuid(), nullable=False))
    op.alter_column('permission', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_permission_name'), 'permission', type_='unique')
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=True)
    op.create_foreign_key(op.f('fk_permission_owner_id_user'), 'permission', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_permission_editor_id_user'), 'permission', 'user', ['editor_id'], ['id'], ondelete='CASCADE')
    op.add_column('role', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.add_column('role', sa.Column('editor_id', sa.Uuid(), nullable=False))
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_role_name'), 'role', type_='unique')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_foreign_key(op.f('fk_role_editor_id_user'), 'role', 'user', ['editor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_role_owner_id_user'), 'role', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_role_owner_id_user'), 'role', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_editor_id_user'), 'role', type_='foreignkey')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_unique_constraint(op.f('uq_role_name'), 'role', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('role', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('role', 'editor_id')
    op.drop_column('role', 'owner_id')
    op.drop_constraint(op.f('fk_permission_editor_id_user'), 'permission', type_='foreignkey')
    op.drop_constraint(op.f('fk_permission_owner_id_user'), 'permission', type_='foreignkey')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.create_unique_constraint(op.f('uq_permission_name'), 'permission', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('permission', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('permission', 'editor_id')
    op.drop_column('permission', 'owner_id')
    # ### end Alembic commands ###
