"""add saft fields to organization

Revision ID: 7b2c2b2c2b2c
Revises: 6a1b1a1b1a1b
Create Date: 2025-12-14 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2c2b2c2b2c'
down_revision = '6a1b1a1b1a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('region_code', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('default_currency', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('tax_basis', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'tax_basis')
    op.drop_column('organization', 'default_currency')
    op.drop_column('organization', 'region_code')
    # ### end Alembic commands ###
