"""add eik to organization

Revision ID: 8c3d3d3d3d3d
Revises: 7b2c2b2c2b2c
Create Date: 2025-12-14 17:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3d3d3d3d3d'
down_revision = '7b2c2b2c2b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('eik', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'eik')
    # ### end Alembic commands ###
