"""add accounting config to organization

Revision ID: a1b2c3d4e5f6
Revises: 9d4d4d4d4d4d
Create Date: 2025-12-14 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9d4d4d4d4d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('accounts_receivable_account_id', sa.UUID(), nullable=True))
    op.add_column('organization', sa.Column('sales_revenue_account_id', sa.UUID(), nullable=True))
    op.add_column('organization', sa.Column('vat_payable_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organization', 'account', ['accounts_receivable_account_id'], ['id'])
    op.create_foreign_key(None, 'organization', 'account', ['sales_revenue_account_id'], ['id'])
    op.create_foreign_key(None, 'organization', 'account', ['vat_payable_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'vat_payable_account_id')
    op.drop_column('organization', 'sales_revenue_account_id')
    op.drop_column('organization', 'accounts_receivable_account_id')
    # ### end Alembic commands ###
