"""Add stock transfer table

Revision ID: a88ad8dbb50d
Revises: 33382b9ecacc
Create Date: 2025-05-09 20:47:15.171266

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a88ad8dbb50d'
down_revision = '33382b9ecacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfer',
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_transfer', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('src_store_id', sa.Uuid(), nullable=False),
    sa.Column('dst_store_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dst_store_id'], ['store.id'], name=op.f('fk_stock_transfer_dst_store_id_store'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_stock_transfer_item_id_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_stock_transfer_owner_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_store_id'], ['store.id'], name=op.f('fk_stock_transfer_src_store_id_store'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_transfer')
    # ### end Alembic commands ###
