"""add purchase accounting config to organization

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2025-12-14 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('inventory_account_id', sa.UUID(), nullable=True))
    op.add_column('organization', sa.Column('accounts_payable_account_id', sa.UUID(), nullable=True))
    op.add_column('organization', sa.Column('vat_deductible_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organization', 'account', ['inventory_account_id'], ['id'])
    op.create_foreign_key(None, 'organization', 'account', ['accounts_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'organization', 'account', ['vat_deductible_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'vat_deductible_account_id')
    op.drop_column('organization', 'accounts_payable_account_id')
    op.drop_column('organization', 'inventory_account_id')
    # ### end Alembic commands ###
