"""create asset tables

Revision ID: d4e5f6a7b8c9
Revises: a1b2c3d4e5f6
Create Date: 2025-12-14 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4e5f6a7b8c9'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('inventory_number', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('responsible_person', sa.String(), nullable=True),
    sa.Column('tax_category', sa.String(), nullable=True),
    sa.Column('tax_depreciation_rate', sa.Float(), nullable=True),
    sa.Column('accounting_depreciation_rate', sa.Float(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('acquisition_cost', sa.Float(), nullable=False),
    sa.Column('startup_date', sa.Date(), nullable=True),
    sa.Column('purchase_order_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('salvage_value', sa.Float(), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('depreciation_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('residual_value', sa.Float(), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_reason', sa.String(), nullable=True),
    sa.Column('disposal_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('month_value_change', sa.Integer(), nullable=True),
    sa.Column('month_suspension_resumption', sa.Integer(), nullable=True),
    sa.Column('month_writeoff_accounting', sa.Integer(), nullable=True),
    sa.Column('month_writeoff_tax', sa.Integer(), nullable=True),
    sa.Column('depreciation_months_current_year', sa.Integer(), nullable=True),
    sa.Column('acquisition_cost_begin_year', sa.Float(), nullable=True),
    sa.Column('book_value_begin_year', sa.Float(), nullable=True),
    sa.Column('accumulated_depreciation_begin_year', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('accounting_account_id', sa.UUID(), nullable=True),
    sa.Column('expense_account_id', sa.UUID(), nullable=True),
    sa.Column('accumulated_depreciation_account_id', sa.UUID(), nullable=True),
    sa.Column('disposal_journal_entry_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['accounting_account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['accumulated_depreciation_account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disposal_journal_entry_id'], ['journal_entry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_code'), 'asset', ['code'], unique=False)
    op.create_index(op.f('ix_asset_inventory_number'), 'asset', ['inventory_number'], unique=False)
    op.create_index(op.f('ix_asset_organization_id'), 'asset', ['organization_id'], unique=False)
    op.create_table('asset_depreciation_schedule',
    sa.Column('depreciation_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('book_value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_depreciation_schedule_organization_id'), 'asset_depreciation_schedule', ['organization_id'], unique=False)
    op.create_table('asset_transaction',
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transaction_amount', sa.Float(), nullable=False),
    sa.Column('acquisition_cost_change', sa.Float(), nullable=True),
    sa.Column('book_value_after', sa.Float(), nullable=True),
    sa.Column('saft_transaction_id', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('supplier_customer_id', sa.UUID(), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_customer_id'], ['supplier.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_transaction_organization_id'), 'asset_transaction', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_transaction_organization_id'), table_name='asset_transaction')
    op.drop_table('asset_transaction')
    op.drop_index(op.f('ix_asset_depreciation_schedule_organization_id'), table_name='asset_depreciation_schedule')
    op.drop_table('asset_depreciation_schedule')
    op.drop_index(op.f('ix_asset_organization_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_inventory_number'), table_name='asset')
    op.drop_index(op.f('ix_asset_code'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
