/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as SaftImport } from './routes/saft'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutVatImport } from './routes/_layout/vat'
import { Route as LayoutStoresImport } from './routes/_layout/stores'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutInvoicesImport } from './routes/_layout/invoices'
import { Route as LayoutCurrenciesImport } from './routes/_layout/currencies'
import { Route as LayoutContraagentsImport } from './routes/_layout/contraagents'
import { Route as LayoutAssetsImport } from './routes/_layout/assets'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutAccountsImport } from './routes/_layout/accounts'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SaftRoute = SaftImport.update({
  path: '/saft',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutVatRoute = LayoutVatImport.update({
  path: '/vat',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoresRoute = LayoutStoresImport.update({
  path: '/stores',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutInvoicesRoute = LayoutInvoicesImport.update({
  path: '/invoices',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCurrenciesRoute = LayoutCurrenciesImport.update({
  path: '/currencies',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutContraagentsRoute = LayoutContraagentsImport.update({
  path: '/contraagents',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAssetsRoute = LayoutAssetsImport.update({
  path: '/assets',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAccountsRoute = LayoutAccountsImport.update({
  path: '/accounts',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/saft': {
      preLoaderRoute: typeof SaftImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/accounts': {
      preLoaderRoute: typeof LayoutAccountsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/assets': {
      preLoaderRoute: typeof LayoutAssetsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/contraagents': {
      preLoaderRoute: typeof LayoutContraagentsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/currencies': {
      preLoaderRoute: typeof LayoutCurrenciesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/invoices': {
      preLoaderRoute: typeof LayoutInvoicesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/stores': {
      preLoaderRoute: typeof LayoutStoresImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/vat': {
      preLoaderRoute: typeof LayoutVatImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAccountsRoute,
    LayoutAdminRoute,
    LayoutAssetsRoute,
    LayoutContraagentsRoute,
    LayoutCurrenciesRoute,
    LayoutInvoicesRoute,
    LayoutSettingsRoute,
    LayoutStoresRoute,
    LayoutVatRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SaftRoute,
  SignupRoute,
])

/* prettier-ignore-end */
